const recipes = [
      {
    name: 'Chleb żytni 2000 na drożdżach',
    whichMeal: "inne",
    kcal: 1786,
    mom: 1,
    me: 1,
    ingredients: [
      {ingrName: 'mąka żytnia razowa, typ 2000', amount: 500, unit: 'g'},
      {ingrName: 'sól', amount: "1,5", unit: 'łyżeczki'},
      {ingrName: 'drożdże świeże/ drożdże instant', amount: "25 / 7", unit: "g"},
      {ingrName: 'cukier', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'ciepła woda', amount: 400, unit: "ml"},
      {ingrName: 'olej lub oliwa o neutralnym smaku', amount: 2, unit: "łyżki"},
      {ingrName: 'olej do wysmarowania formy'},
      {ingrName: 'otręby i płatki owsiane do posypania (opcjonalnie)'},
    ],
    steps: [
      "Zaczyn: drożdże wkruszyć do miseczki, zasypać cukrem, wlać kilka łyżek ciepłej wody i odstawić w ciepłe miejsce na 15 minut.",
      "Do misy mieszającej wsypać mąkę, dodać sól, zaczyn, resztę ciepłej wody i olej.",
      "Wyrabiać przez około 5 minut [5 min / ???]. Ciasto będzie mocno klejące, ważne by dobrze je wyrobić.",
      "Keksówkę 22&times;10 cm wysmarować olejem i wysypać otrębami (dno i boki). Można zamiast tego wyłożyć papierem do pieczenia.",
      "Do formy przełożyć ciasto przy pomocy łyżki i wyrównać je dłonią zwilżoną zimną wodą. Wierzch posypać płatkami, lekko je docisnąć. Zawinąć w czystą ścierkę i odstawić w ciepłe miejsce na około 1,5-2 godziny.",
      "Piec w 200&deg;C (góra-dół) przez około 45-50 minut (lub dłużej, aż skórka będzie chrupiąca. (Po 45 minutach można wyjąć ostrożnie z formy i postukać w spód - powinien wydać głuchy dźwięk. W razie potrzeby włożyć z powrotem do formy, spodem do góry i dopiec kilka minut.)",
      "Studzić na metalowej kratce, kroić po całkowitym ostudzeniu."
    ],
    time: "45 minut + 2h wyrastanie + studzenie",
    notes: "Wyrabiać tylko do połączenia składników. Ciężkie chleby nie lubią długiego wyrabiania. Nie powinno też \"przerosnąć\". Chleb z mąki żytniej typu 2000 jest dość ciężki, trochę \"gliniasty\" i zawsze po upieczeniu trzeba dać mu czas na odpoczynek i całkowite ostygnięcie. Ma wyraźny, lekko orzechowy posmak i ciemny kolor.",
    imgSrc: "./images/chleb_zytni_2000.jpg"
  },
  {
    name: 'Parówki z chrzanem, sałatka z ogórka kiszonego i pomidora',
    whichMeal: "śniadanie",
    kcal: 360,
    mom: 2,
    me: 1,
    ingredients: [
      {ingrName: 'parówki', amount: 2, unit: 'sztuki', gram: 100},
      {ingrName: 'chrzan tarty / musztarda', amount: 2, unit: 'łyżeczki'},
      {ingrName: 'cebula (np. dymka)', amount: 1, unit: 'sztuka'},
      {ingrName: 'ogórek kiszony', amount: 1, unit: 'sztuka'},
      {ingrName: 'pomidor', amount: 1, unit: 'sztuka'},
      {ingrName: 'sałata, kiełki'},
    ],
    steps: [
      "Parówki zagotować.",
      "Podawać z chrzanem lub musztardą i sałatką z sałaty, ogórka kiszonego pokrojonego w plastry i pomidora z cebulką."
    ],
    time: "5 minut",
    notes: "Parówki dobrej jakości, z wysoką zawartością mięsa (np. w Lidlu z serii PURE lub w Biedronce z serii NATUR). <br/> Za dużo cebuli. Dla mnie lepsze z dodatkowym pomidorem zamiast ogórka kiszonego.",
    imgSrc: "./images/parowki_z_chrzanem.jpg"
  },
  {
    name: 'Bakaliowy deser z jogurtem i mandarynką',
    whichMeal: "drugie śniadanie",
    kcal: 280,
    mom: 1,
    me: 1,
    ingredients: [
      {ingrName: 'jogurt naturalny', amount: 150, unit: 'g'},
      {ingrName: 'mandarynka', amount: 1, unit: 'sztuka'},
      {ingrName: 'miód', amount: 1, unit: 'łyżeczka', gram: 8},
      {ingrName: 'orzechy włoskie', amount: 1, unit: 'łyżka', gram: 15},
      {ingrName: 'rodzynki', amount: 1, unit: 'łyżka', gram: 15},
    ],
    steps: [
      "Mandarynkę obrać i podzielić na kawałki.",
      "Orzechy posiekać.",
      "Wymieszać rodzynki z mandarynką, orzechami i jogurtem.",
      "Polać miodem."
    ],
    time: "5 minut",
    notes: "Zamiast mandarynki można dodać 5-6 truskawek (100g), żeby zachować tę samą liczbę kalorii.",
    imgSrc: "./images/bakaliowy_deser.jpg"
  },
  {
    name: 'Kurczak szarpany w bułce',
    whichMeal: "obiad",
    kcal: 400,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'filet z piersi kurczaka', amount: 200, unit: 'g'},
      {ingrName: 'natka pietruszki / kolendra', amount: "1-2", unit: 'gałązki'},
      {ingrName: 'czosnek', amount: 1, unit: 'ząbek'},
      {ingrName: 'pomidory w puszce', amount: 200, unit: 'g'},
      {ingrName: 'sos sojowy', amount: "1,5", unit: 'łyżki', gram: 15},
      {ingrName: 'erytrol', amount: "1/2", unit: 'łyżeczki'},
      {ingrName: 'słodka papryka', amount: "1/2", unit: 'łyżeczki'},
      {ingrName: 'ostra papryka [opcjonalnie]', amount: "1/4", unit: 'łyżeczki'},
      {ingrName: 'wędzona papryka', amount: "1/4", unit: 'łyżeczki'},
      {ingrName: 'bułka grahamka (na 1 porcję)', amount: 1, unit: 'sztuka', gram: 100},
      {ingrName: 'sałata lodowa'},
      {ingrName: 'cebula czerwona', amount: "kilka", unit: 'piórek'},
      {ingrName: 'ogórki konserwowe', amount: "kilka", unit: 'plastrów'},
      {ingrName: 'pomidor', amount: 2, unit: 'grube plastry'},
    ],
    steps: [
      "Mięso pokroić w dość grubą kostkę (3-4 cm).",
      "W naczyniu miksującym umieścić natkę pietruszki i czosnek, rozdrobnić [3 s / obr. 8]. Składniki zgarnąć kopystką.",
      "Dodać pomidory, mięso z kurczaka, sos sojowy, erytrol, słodką, ostrą i wędzoną paprykę. Zamiast miarki na pokrywę naczynia miksującego nałożyć koszyczek, odparowywać [20 min / Varoma / obr. wsteczne 1].",
      "Założyć miarkę, rozdrobnić [4 s / obr. wsteczne 4].",
      "Bułki podgrzać w tosterze.",
      "Na bułce ułożyć sałatę, szarpane mięso, posypać liśćmi świeżej pietruszki.",
      "Na mięso ułożyć pół-talarki cebuli, kilka plastrów ogórka i gruby plaster pomidora, przykryć drugą połową bułki."
    ],
    time: "40 minut",
    notes: "2 porcje <br/> Naczynie się przypala, trzeba pilnować i podlewać wodą, ewentualnie spróbować dusić z miarką zamiast koszyczka. <br/> Bułkę można podgrzać na suchej patelni z każdej strony.",
    imgSrc: "./images/kurczak_szarpany.jpg"
  },
  {
    name: 'Zupa krem z pomidorów z mozzarellą',
    whichMeal: "kolacja",
    kcal: 350,
    mom: 0,
    me: 1,
    ingredients: [
      {ingrName: 'cebula', amount: 1, unit: 'sztuka'},
      {ingrName: 'czosnek', amount: "1-2", unit: 'ząbki'},
      {ingrName: 'olej kokosowy', amount: 1, unit: 'łyżka', gram: 10},
      {ingrName: 'pomidory w puszce', amount: "1,5", unit: 'sztuki', gram: 600},
      {ingrName: 'bazylia świeża'},
      {ingrName: 'ser mozzarella (kulka)', amount: 1, unit: 'sztuka', gram: 100},
      {ingrName: 'dynia (pestki)', amount: 2, unit: 'łyżki', gram: 20},
      {ingrName: 'oregano, sól, pieprz'},
    ],
    steps: [
      "Do naczynia miksującego włożyć cebulę i czosnek, rozdrobnić [5 s / obr. 5], składniki zgarnąć kopystką, dodać olej i dusić [2 min / 120&deg;C / obr. 1].",
      "Dodać pomidory i przyprawy (sól, pieprz, oregano), dusić [10 min / 100&deg;C / obr. 2].",
      "Dodać kilka listków bazylii i zmiksować [ok. 30-40 s / obr. 4-10 (stopniowo zwiększać obroty)].",
      "Podawać z listkami świeżęj bazylii i pokruszonym serem mozzarella, posypać pestkami dyni."
    ],
    time: "20 minut",
    notes: "2 porcje <br/> Bardzo kwaśna. Może spróbować ze świeżych pomidorów albo dodać erytrolu.",
    imgSrc: "./images/zupa_krem_z_pomidorow.jpg"
  },
  {
    name: 'FIT pasta jajeczna',
    whichMeal: "śniadanie",
    kcal: 380,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'jajka', amount: 3, unit: 'sztuki'},
      {ingrName: 'papryka czerwona', amount: "1/2", unit: 'sztuki'},
      {ingrName: 'szczypiorek'},
      {ingrName: 'jogurt grecki', amount: 2, unit: 'łyżki', gram: 50},
      {ingrName: 'majonez', amount: 1, unit: 'łyżeczka', gram: 10},
      {ingrName: 'musztarda', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'sól, pieprz ziołowy i czarny'},
      {ingrName: 'chleb żytni', amount: 4, unit: 'kromki'},
      {ingrName: 'natka pietruszki'},
      {ingrName: 'pomidor', amount: 1, unit: 'sztuka'},
      {ingrName: 'ogórek kiszony', amount: 1, unit: 'sztuka'},
      {ingrName: 'sałata lodowa'},
      {ingrName: 'kiełki'},
    ],
    steps: [
      "Jajka ugotować na twardo [14 min / Varoma / obr. 1]. Pozostawić do ostudzenia.",
      "Paprykę pokroić w kosteczkę (ewentualnie rozdrobnić [5 s / obr. 4]).", 
      "Szczypiorek posiekać.",
      "Ostudzone jajka pokroić w drobną kostkę.",
      "Całość wymieszać z jogurtem, musztardą, majonezem i przyprawami [10 s / obr. wsteczne 1,5].",
      "Ułożyć na chlebie żytnim, posypać pietruszką. Można obłożyć pomidorem i ogórkiem oraz kiełkami."
    ],
    time: "20 minut",
    notes: "2 porcje",
    imgSrc: "./images/fit_pasta_jajeczna.jpg"
  },
  {
    name: 'Czekoladowe placki z malinami',
    whichMeal: "drugie śniadanie",
    kcal: 330,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'jogurt naturalny, gęsty', amount: 140, unit: 'g'},
      {ingrName: 'jajko', amount: 1, unit: 'sztuka'},
      {ingrName: 'ekstrakt z wanilii', amount: "1/2", unit: 'łyżeczki'},
      {ingrName: 'erytrol', amount: 1, unit: 'łyżka', gram: 10},
      {ingrName: 'kakao', amount: 1, unit: 'łyżka', gram: 10},
      {ingrName: 'proszek do pieczenia', amount: "1/2", unit: 'łyżeczki'},
      {ingrName: 'mąka orkiszowa/owsiana', amount: 70, unit: 'g'},
      {ingrName: 'olej kokosowy', amount: 1, unit: 'łyżka', gram: 10},
      {ingrName: 'maliny', amount: 100, unit: 'g'},
      {ingrName: 'syrop klonowy', amount: 2, unit: 'łyżki'},
    ],
    steps: [
      "W naczyniu miksującym umieścić jogurt, jajko, ekstrakt z wanilii, erytrol, kakao, mąkę orkiszową/owsianą, proszek do pieczenia i wymieszać [20 s / obr. 3,5] (w razie potrzeby zgarnąć kopystką, czynność powtórzyć).",
      "Patelnię rozgrzać i nasmarować niewielką ilością oleju.",
      "Za pomocą łyżki układać placki, a następnie na każdym placku układać maliny (lekko wcisnąć). Kilka malin można zostawić do dekoracji.",
      "Zmniejszyć ogień, patelnię przykryć, usmażyć z obu stron.",
      "Placki polać syropem klonowym, udekorować owocami.",
      "Podawać na zimno lub na ciepło."
    ],
    time: "25 minut",
    notes: "2 porcje <br/> Maliny przywierają do patelni - może lepiej usmażyć placki bez malin i podać je osobno.",
    imgSrc: "./images/czekoladowe_placki_z_malinami.jpg"
  },
  {
    name: 'Gulasz z kaszą',
    whichMeal: "obiad",
    kcal: 430,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'wieprzowina (schab surowy)', amount: 500, unit: 'g'},
      {ingrName: 'papryka słodka', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'papryka ostra', amount: "1/2", unit: 'łyżeczki'},
      {ingrName: 'sól, pieprz'},
      {ingrName: 'marchew', amount: 2, unit: 'sztuki', gram: 90},
      {ingrName: 'pietruszka', amount: "1/2", unit: 'sztuki', gram: 40},
      {ingrName: 'cebula', amount: "1,5", unit: 'sztuki', gram: 150},
      {ingrName: 'masło klarowane', amount: 1, unit: 'łyżka', gram: 15},
      {ingrName: 'bulion (z koncentratu bulionu z TM)', amount: 2, unit: 'szklanki', gram: 500},
      {ingrName: 'mąka z ciecierzycy', amount: 1, unit: 'łyżka', gram: 10},
      {ingrName: 'kasza gryczana', amount: 200, unit: 'g'},
      {ingrName: 'ogórki kiszone', amount: 4, unit: 'spore sztuki'},
      {ingrName: 'por', amount: "1/2", unit: 'sztuki', gram: 50},
      {ingrName: 'oliwa z oliwek', amount: 1, unit: 'łyżka'},
      {ingrName: 'ocet winny/jabłkowy', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'erytrol', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'pieprz', amount: 1, unit: 'szczypta'},
    ],
    steps: [
      "Mięso pokroić w kostkę. Wrzucić do miski, dodać papryki, sól, pieprz wg uznania.",
      "Marchewkę i pietruszkę pokroić w pół-plasterki.",
      "Cebulę rozdrobnić [5 s / obr. 5], zgarnąć kopystką. Dodać 1 łyżkę masła klarowanego i dusić [3 min / 120&deg;C / obr. wsteczne 1].",
      "Dodać mięso i dusić [6 min / 120&deg;C / obr. wsteczne 1].",
      "Dorzucić marchewkę i pietruszkę, zalać bulionem i gotować [40-50 min / 100&deg;C / obr. wsteczne ???]",
      "Do małego słoika wsypać łyżkę mąki z ciecierzycy, dolać odrobinę wody, zakręcić, rozmieszać i dolać do gulaszu. Gotować kolejne [2 min / 100&deg;C / obr. wsteczne 0,5].",
      "Kaszę ugotować w garnku lub w TM (w koszyku, 1l wody, [18-20 min / Varoma / obr. 4]).",
      "Ogórki pokroić w cienkie plasterki lub w kosteczkę, dodać por pokrojony w cienkie pół-talarki.",
      "Wymieszać z oliwą, octem, pieprzem i erytrolem."
    ],
    time: "1 godzina 20 minut",
    notes: "4 porcje <br/> Kaszy nie należy gotować w woreczku!!!!",
    imgSrc: "./images/gulasz_z_kasza.jpg"
  },
  {
    name: 'Sałatka z grillowanymi warzywami',
    whichMeal: "kolacja",
    kcal: 320,
    mom: 0,
    me: 2,
    ingredients: [
      {ingrName: 'cebula czerwona', amount: "1/2", unit: 'sztuki'},
      {ingrName: 'cukinia', amount: "ok. 100", unit: 'g'},
      {ingrName: 'papryka czerwona', amount: "1/2", unit: 'sztuki'},
      {ingrName: 'pieczarki', amount: 4, unit: 'sztuki', gram: 100},
      {ingrName: 'fasola szparagowa', amount: 50, unit: 'g'},
      {ingrName: 'oliwa', amount: 1, unit: 'łyżka', gram: 10},
      {ingrName: 'sałata lodowa/mix sałat', amount: 2, unit: 'garście'},
      {ingrName: 'sos winegret', amount: "1,5 - 2", unit: 'łyżki'},
      {ingrName: 'parmezan tarty', amount: 1, unit: 'łyżka', gram: 12},
      {ingrName: 'zioła prowansalskie'},
      {ingrName: 'listki oregano (opcjonalnie)'},
    ],
    steps: [
      "Warzywa pokroić w plasterki i przyprawić ziołami prowansalskimi, skropić odrobiną oliwy.",
      "Opiekać na patelni grillowej lub w piekarniku na funkcji grill aż zmiękną.",
      "Mix sałat wyłożyć na talerz, polać sosem winegret.",
      "Dodać warzywa.",
      "Całość posypać parmezanem. Opcjonalnie udekorować listkami oregano."
    ],
    time: "40 minut",
    notes: "Sos winegret - w innym przepisie.",
    imgSrc: "./images/salatka_z_grillowanymi_warzywami.jpg"
  },
  {
    name: 'Sos winegret',
    whichMeal: "inne",
    kcal: "???",
    mom: null,
    me: null,
    ingredients: [
      {ingrName: 'czosnek', amount: 1, unit: 'ząbek'},
      {ingrName: 'oliwa z oliwek', amount: 35, unit: 'g'},
      {ingrName: 'sok z cytryny / ocet balsamiczny/ winny/ jabłkowy', amount: "15-20", unit: 'g'},
      {ingrName: 'musztarda DIJON/miodowa', amount: "1,5", unit: 'łyżeczki', gram: 15},
      {ingrName: 'miód', amount: "1,5", unit: 'łyżeczki'},
      {ingrName: 'sól', amount: "1/4", unit: 'łyżeczki'},
      {ingrName: 'pieprz', amount: 1, unit: 'szczypta'},
    ],
    steps: [
      "Czosnek rozdrobnić [3 s / obr. 8], zgarnąć kopystką.",
      "Dodać oliwę, sok z cytryny, musztardę, miód, sól i pieprz. Wymieszać [12 s / obr 3]."
    ],
    time: "3 minuty",
    notes: "5 porcji (na 1 porcję przypada ok. 1,5 - 2 łyżek sosu) <br/> Można przyrządzić z podwójnej porcji i przechowywać w lodówce.",
    imgSrc: "./images/sos_winegret.jpg"
  },
  {
    name: 'Owsianka BOUNTY',
    whichMeal: "śniadanie",
    kcal: 390,
    mom: 0,
    me: 1,
    ingredients: [
      {ingrName: 'płatki owsiane', amount: 4, unit: 'łyżki', gram: 35},
      {ingrName: 'woda', amount: 220, unit: 'g'},
      {ingrName: 'wiórki kokosowe', amount: 1, unit: 'łyżka', gram: 6},
      {ingrName: 'mleczko kokosowe', amount: 7, unit: 'łyżek', gram: 60},
      {ingrName: 'erytrol', amount: 1, unit: 'łyżka', gram: 10},
      {ingrName: 'czekolada gorzka (min. 70%)', amount: 2, unit: 'kostki', gram: 20},
      {ingrName: 'maliny', amount: "3/4", unit: 'szklanki', gram: 100},
    ],
    steps: [
      "Płatki umieścić w naczyniu miksującym, dodać wodę i wiórki.",
      "Jeżeli maliny są mrożone, umieścić je w koszyczku.",
      "Gotować przez [12 min / 100&deg;C / obr. wsteczne 1].",
      "Dodać mleko kokosowe oraz erytrol, wymieszać [6 s / obr. wsteczne 2,5].",
      "Odstawić na ok. 10 minut, aż zgęstnieje.",
      "Przełożyć do miseczek, na wierzchu posypać kawałkami czekolady i malinami."
    ],
    time: "25 minut",
    notes: "Bardzo mało słodka, raczej kwaśna od malin. Może użycie świeżych malin by pomogło, ewentualnie trochę erytrolu do smaku.",
    imgSrc: "./images/owsianka_bounty.jpg"
  },
  {
    name: 'Sałatka z parmezanem',
    whichMeal: "drugie śniadanie",
    kcal: 290,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'mix sałat', amount: 2, unit: 'garście'},
      {ingrName: 'suszone pomidory', amount: 2, unit: 'plastry', gram: 15},
      {ingrName: 'pomidorki koktajlowe', amount: 5, unit: 'sztuk', gram: 100},
      {ingrName: 'ser parmezan, płatki', amount: 25, unit: 'g'},
      {ingrName: 'słonecznik łuskany', amount: 1, unit: 'łyżka'},
      {ingrName: 'sos winegret', amount: "1,5 - 2", unit: 'łyżki'},
    ],
    steps: [
      "Sałatę ułożyć na talerzu.",
      "Dodać pokrojone suszone pomidory i połówki pomidorków koktajlowych.",
      "Posypać prażonym słonecznikiem, parmezanem i polać sosem winegret."
    ],
    time: "5 minut",
    notes: "Sos winegret - w innym przepisie.",
    imgSrc: "./images/salatka_z_parmezanem.jpg"
  },
  {
    name: 'Pstrąg z kapustą kiszoną',
    whichMeal: "obiad",
    kcal: 400,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'pstrąg, filet', amount: 200, unit: 'g'},
      {ingrName: 'sól, pieprz, rozmaryn'},
      {ingrName: 'cytryna'},
      {ingrName: 'oliwa z oliwek', amount: "1 + 1", unit: 'łyżeczka'},
      {ingrName: 'natka pietruszki', amount: 2, unit: 'łyżeczki', gram: 10},
      {ingrName: 'marchew', amount: "1/2", unit: 'sztuki'},
      {ingrName: 'erytrol', amount: "1/2", unit: 'łyżeczki'},
      {ingrName: 'kapusta kiszona', amount: 1, unit: 'szklanka', gram: 100},
    ],
    steps: [
      "Piekarnik rozgrzać do 250&deg;C.",
      "Rybę umieścić w naczyniu żaroodpornym, skropić sokiem z cytryny, oprószyć pieprzem, solą i rozmarynem (można dodać świeży), skropić 1 łyżką oliwą.",
      "Zapiekać 10-15 minut. W tym czasie przygotować surówkę.",
      "W naczyniu miksującym rozdrobnić natkę [10 s / obr. 10]. Zgarnąć kopystką (można posiekać nożem).",
      "Dodać marchew, 1 łyżkę oliwy, erytrol i pieprz. Rozdrobnić [3 s / obr. 5], zgarnąć kopystką.",
      "Dodać kapustę i rozdrobnić [3-4 s / obr. 5]."
    ],
    time: "30 minut",
    notes: "Ryba będzie niedosolona jeśli tylko posypać ją po troszku z solniczki.",
    imgSrc: "./images/pstrag_z_kapusta_kiszona.jpg"
  },
  {
    name: 'Makaron ze szpinakiem i serem Feta',
    whichMeal: "kolacja",
    kcal: 360,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'makaron pełnoziarnisty', amount: "1/2", unit: 'szklanki', gram: 60},
      {ingrName: 'oliwa', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'czosnek', amount: 1, unit: 'ząbek'},
      {ingrName: 'szpinak świeży', amount: 150, unit: 'g'},
      {ingrName: 'jogurt naturalny', amount: 1, unit: 'łyżka', gram: 20},
      {ingrName: 'ser typu Feta, półtłusty', amount: 30, unit: 'g'},
      {ingrName: 'gałka muszkatołowa, sól, pieprz biały i czarny'},
    ],
    steps: [
      "Makaron ugotować.",
      "Na patelni rozgrzać oliwę, podsmażyć rozgnieciony czosnek, dodać szpinak (można poszarpać) i dusić (w razie potrzeby podlać niewielką ilością wody).",
      "Dodać jogurt oraz pokruszoną fetę, wymieszać i dusić, aż ser się nieco rozpuści.",
      "Przyprawić do smaku, dodać makaron i wymieszać."
    ],
    time: "20 minut",
    notes: "",
    imgSrc: "./images/makaron_ze_szpinakiem.jpg"
  },
  {
    name: 'Omletost',
    whichMeal: "śniadanie",
    kcal: 430,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'jajko', amount: 1, unit: 'sztuka'},
      {ingrName: 'jogurt grecki', amount: 1, unit: 'łyżka', gram: 20},
      {ingrName: 'sól, pieprz'},
      {ingrName: 'szynka szwarcwaldzka', amount: 1, unit: 'plaster', gram: 20},
      {ingrName: 'oliwa z oliwek', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'chleb żytni', amount: 2, unit: "kromki"},
      {ingrName: 'pomidor', amount: "1-2", unit: "plastry"},
      {ingrName: 'ogórek kiszony', amount: 1, unit: "sztuka"},
      {ingrName: 'papryka', amount: "kilka", unit: "słupków"},
      {ingrName: 'ser żółty/parmezan', amount: 1, unit: "plaster", gram: 20},
      {ingrName: 'szpinak', amount: 1, unit: "garść"},
      {ingrName: 'ketchup (opcjonalnie)'},
    ],
    steps: [
      "Jajko roztrzepać z jogurtem, solą i pieprzem [15 s / obr. 4].",
      "Na suchej patelni podpiec 2-3 minuty szynkę.",
      "Rozgrzaną patelnię posmarować oliwą lub masłem klarowanym. Wylać masę, położyć na środku 2 kromki chleba (obok siebie).",
      "Gdy jajka się zetną, przewrócić na drugą stronę.",
      "Na jednej kromce ułożyć ser, chips z szynki, plasterki pomidora, ogórka i paprykę. Smażyć na niedużym ogniu pod przykryciem, aż ser się lekko roztopi.",
      "Dodać szpinak, można polać ketchupem.",
      "Kanapki złożyć w pół (tak, aby powstał tost z omletem i dodatkami w środku)."
    ],
    time: "25 minut",
    notes: "",
    imgSrc: "./images/omletost.jpg"
  },
  {
    name: 'Puszysty FIT sernik',
    whichMeal: "drugie śniadanie",
    kcal: 260,
    mom: 0,
    me: 1,
    ingredients: [
      {ingrName: 'jajko', amount: 2, unit: 'sztuki'},
      {ingrName: 'twaróg półtłusty', amount: 200, unit: 'g'},
      {ingrName: 'jogurt naturalny', amount: 200, unit: 'g'},
      {ingrName: 'budyń śmietankowy bez cukru', amount: 1, unit: 'opakowanie', gram: 40},
      {ingrName: 'erytrol', amount: 40, unit: "g"},
      {ingrName: 'dowolne owoce (mogą być mrożone) np. maliny, borówki, owoce leśne', amount: 200, unit: "g"},
      {ingrName: 'czekolada gorzka (min. 70%)', amount: 4, unit: "kostki", gram: 40},
    ],
    steps: [
      "Białka ubić na pianę [motylek ok. 2,5 min. / obr. 3,5], przełożyć delikatnie do miseczki",
      "Twaróg, jogurt, żółtka, budyń w proszku i erytrol wymieszać [30 s / obr. 5].",
      "Dodać pianę i delikatnie wymieszać.",
      "Dodać owoce (część można zostawić do ozdoby) i ponownie przemieszać.",
      "Puszystą masę przełożyć do okrągłej foremki (18cm) lub do małej jednorazowej keksówki (18&times;8), można też użyć kokilek.",
      "Piec w piekarniku góra/dół 180&deg;C przez 40 minut.",
      "Po ostudzeniu posypać tartą czekoladą."
    ],
    time: "55 minut + studzenie",
    notes: "4 porcje <br/> Zrobić poprzedniego dnia i schłodzić w lodówce. Przy podanej ilości mrożonych owoców leśnych bardzo kwaśne - spróbować z połowy i z cukrem pudrem z erytrolu.",
    imgSrc: "./images/puszysty_fit_sernik.jpg"
  },
  {
    name: 'Pulpeciki w sosie kokosowym i marchewka z groszkiem',
    whichMeal: "obiad",
    kcal: 440,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'koperek', amount: 1, unit: 'czubata łyżka', gram: 10},
      {ingrName: 'indyk, mięso mielone', amount: 200, unit: 'g'},
      {ingrName: 'pieprz, sól, słodka papryka'},
      {ingrName: 'olej kokosowy', amount: 1, unit: 'łyżka', gram: 10},
      {ingrName: 'mleczko kokosowe', amount: 200, unit: "g"},
      {ingrName: 'musztarda', amount: 1, unit: "łyżeczka", gram: 10},
      {ingrName: 'sok z cytryny', amount: 1, unit: "łyżka", gram: 6},
      {ingrName: 'marchewka z groszkiem, mrożona', amount: "1/2", unit: "opakowania", gram: 225},
      {ingrName: 'masło ekstra', amount: 1, unit: "czubata łyżeczka", gram: 15},
      {ingrName: 'woda', amount: "1/5", unit: "szklanki", gram: 50},
      {ingrName: 'sól'},
      {ingrName: 'skrobia ziemniaczana', amount: "1/2", unit: "łyżeczki"},
    ],
    steps: [
      "Do naczynia miksującego włożyć koperek, rozdrobnić [3 s / obr. 8].",
      "Dodać mięso mielone z indyka (jeżeli mięso nie jest mielone, to rozdrobnić [15 s / obr. 6]), sól, pieprz, słodką paprykę i wymieszać [15 s / obr. wsteczne 3,5].",
      "Uformować malutkie klopsiki.",
      "Na patelni rozgrzać olej, obsmażyć kotleciki.",
      "Dodać mleczko kokosowe, musztardę, sok z cytryny i przyprawy. Dusić pod przykryciem kilka minut (ok. 10), aż pulpety dojdą w środku.",
      "Zdjąć pokrywę i gotować na średnim ogniu ciągle mieszając, aż sos zgęstnieje.",
      "Marchewkę z groszkiem rozmrozić lub przelać na sitku ciepłą wodą, aby pozbyć się nadmiaru lodu. Umieścić ją w naczyniu miksującym, dodać masło, wodę i sól. Dusić [10 min / 98&deg;C / obr. wsteczne 1].",
      "Dodać skrobię i groszek, gotować [5 min / 98&deg;C / obr. wsteczne 1].",
      "Klopsiki podawać z gotowaną marchewką z groszkiem."
    ],
    time: "45 minut",
    notes: "2 porcje <br/> Nie przesolić sosu!!",
    imgSrc: "./images/pulpeciki_w_sosie_kokosowym.jpg"
  },
  {
    name: 'Tortilla z warzywami',
    whichMeal: "kolacja",
    kcal: 300,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'tortilla wieloziarnista', amount: 1, unit: 'sztuka'},
      {ingrName: 'sałata lodowa/mix sałat', amount: 1, unit: 'garść'},
      {ingrName: 'ogórek zielony/kiszony', amount: 1, unit: 'sztuka'},
      {ingrName: 'papryka czerwona', amount: "1/4", unit: 'sztuki'},
      {ingrName: 'pomidor', amount: "1/2", unit: 'sztuki'},
      {ingrName: 'cebula czerwona', amount: "1/4", unit: 'sztuki'},
      {ingrName: 'ser typu Feta, półtłusty', amount: 30, unit: 'g'},
      {ingrName: 'czosnek', amount: 1, unit: 'mały ząbek'},
      {ingrName: 'jogurt grecki', amount: 2, unit: 'łyżki'},
    ],
    steps: [
      "Placek podpiec na suchej patelni.",
      "Dodać pokrojone warzywa i fetę.",
      "Polać sosem czosnkowym (jogurt + czosnek przeciśnięty przez praskę).",
      "Tortillę zwinąć w rulon."
    ],
    time: "15 minut",
    notes: "",
    imgSrc: "./images/tortilla_z_warzywami.jpg"
  },
  {
    name: 'Pomarańczowa owsianka z bakaliami i cynamonem',
    whichMeal: "śniadanie",
    kcal: 400,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'morele suszone', amount: 25, unit: 'g'},
      {ingrName: 'jabłko', amount: "1/2", unit: 'sztuki', gram: 90},
      {ingrName: 'napój migdałowy (NIESŁODZONY!)', amount: "1/3", unit: 'szklanki', ml: 100},
      {ingrName: 'płatki owsiane', amount: 3, unit: 'łyżki', gram: 35},
      {ingrName: 'rodzynki', amount: 1, unit: 'łyżka', gram: 8},
      {ingrName: 'cynamon, kardamon', amount: "po szczypcie"},
      {ingrName: 'sok pomarańczowy', amount: "1/3", unit: 'szklanki', gram: 100},
      {ingrName: 'orzechy włoskie', amount: 1, unit: 'łyżka', gram: 10},
    ],
    steps: [
      "W naczyniu miksującym umieścić morele i rozdrobnić [3 s / obr. 7] (jeśli są bardzo twarde, można uprzednio namoczyć kilka minut w gorącej wodzie).",
      "Dodać jabłko i rozdrobnić [4 s / obr. 4], zgarnąć kopystką.",
      "Dodać napój migdałowy, płatki owsiane, rodzynki oraz przyprawy i gotować [8 min / 95&deg;C / obr. wsteczne 1].",
      "Dodać sok pomarańczowy i gotować kolejne [2 min / 95&deg;C / obr. wsteczne 1] (w razie potrzeby można dosłodzić erytrolem i wymieszać).",
      "Przełożyć do miseczki, posypać orzechami."
    ],
    time: "15 minut",
    notes: "",
    imgSrc: "./images/pomaranczowa_owsianka_z_bakaliami.jpg"
  },
  {
    name: 'Sałatka z serem pleśniowym i granatem',
    whichMeal: "drugie śniadanie",
    kcal: 290,
    mom: 2,
    me: 1,
    ingredients: [
      {ingrName: 'rukola/mix sałat', amount: 2, unit: 'garście'},
      {ingrName: 'ser pleśniowy gorgonzola/lazur błękitny', amount: 30, unit: 'g'},
      {ingrName: 'cebula czerwona', amount: "1/4", unit: 'sztuki', gram: 25},
      {ingrName: 'granat', amount: "1/4", unit: 'sztuki', gram: 25},
      {ingrName: 'orzechy włoskie', amount: 1, unit: 'łyżka', gram: 10},
      {ingrName: 'czosnek', amount: 1, unit: 'ząbek'},
      {ingrName: 'świeży sok z pomarańczy (można wycisnąć)', amount: 1, unit: 'łyżka'},
      {ingrName: 'miód', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'oliwa z oliwek', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'ocet balsamiczny', amount: 1, unit: 'łyżeczka'},
    ],
    steps: [
      "Sałatę wyłożyć na talerz.",
      "Ser pleśniowy pokruszyć i dodać do sałaty.",
      "Cebulę pokroić w piórka.",
      "Dodać granat i lekko posiekane orzechy.",
      "Sos: Czosnek drobno posiekać, dodać sok z pomarańczy, oliwę, miód oraz ocet balsamiczny.",
      "Gotowym sosem polać sałatkę."
    ],
    time: "15 minut",
    notes: "",
    imgSrc: "./images/salatka_z_serem_plesniowym.jpg"
  },
  {
    name: 'Leczo',
    whichMeal: "obiad",
    kcal: 370,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'boczek wędzony', amount: 60, unit: 'g'},
      {ingrName: 'oliwa z oliwek', amount: 2, unit: 'łyżki', gram: 20},
      {ingrName: 'kiełbasa (np. drobiowa lub z szynki)', amount: 3, unit: 'sztuki', gram: 300},
      {ingrName: 'cebula', amount: 2, unit: 'sztuki', gram: 200},
      {ingrName: 'czosnek', amount: 2, unit: 'ząbki'},
      {ingrName: 'cukinia', amount: 1, unit: 'sztuka', gram: 250},
      {ingrName: 'papryka czerwona', amount: 1, unit: 'sztuka'},
      {ingrName: 'papryka żółta', amount: 1, unit: 'sztuka'},
      {ingrName: 'fasolka szparagowa (opcjonalnie)', amount: 200, unit: 'g'},
      {ingrName: 'erytrol', amount: 1, unit: 'łyżeczka', gram: 5},
      {ingrName: 'papryka słodka, chili, pieprz, sól, oregano'},
      {ingrName: 'pomidory w puszce', amount: 1, unit: 'sztuka', gram: "350-400"},
    ],
    steps: [
      "Na suchej patelni podsmażyć boczek, dodać 1 łyżkę oliwy, pokrojoną w kostkę kiełbasę i podsmażyć. Odstawić.",
      "Do naczynia miksującego włożyć połówki cebuli i czosnek, rozdrobnić [3 s / obr. 5]. Zgarnąć kopystką.",
      "Dodać 1 łyżkę oliwy i dusić [4 min / 120&deg'C / obr. 1].",
      "Dodać kiełbasę i boczek, pokrojoną w kostkę cukinię (ze skórką), papryki oraz fasolkę pokrojoną  w 4cm kawałki, przyprawić do smaku, dodać erytrol.",
      "Dusić [10 min / 100&deg;C / obr. kopystka ???].",
      "Dodać pomidory w puszce, zamiast miarki na pokrywie naczynia umieścić koszyczek, gotować kolejne [10 min / 100&deg;C / obr. 'kopystka' ???].",
      "Doprawić do smaku."
    ],
    time: "45 minut",
    notes: "4 porcje <br/> Można użyć świeżych pomidorów obranych ze skórki. <br/> Nie szaleć z chili (1 spora czy 2 mniejsze szczypty na całe 4 porcje mocno przyostrzyły).",
    imgSrc: "./images/leczo.jpg"
  },
  {
    name: 'Kanapki z miodem, truskawkami i twarożkiem',
    whichMeal: "kolacja",
    kcal: 330,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'chleb żytni', amount: 2, unit: 'kromki'},
      {ingrName: 'twaróg półtłusty', amount: 50, unit: 'g'},
      {ingrName: 'truskawki', amount: "kilka", unit: 'sztuk'},
      {ingrName: 'miód', amount: "2-3", unit: 'łyżeczki', gram: 20},
      {ingrName: 'orzechy włoskie', amount: 1, unit: 'łyżka', gram: 15},
    ],
    steps: [
      "Na chlebie ułożyć cienkie plasterki twarogu, ułożyć plasterki truskawek, polać miodem i posypać rozdrobnionymi orzechami (można rozdrobnić [3 s / obr. 7])."
    ],
    time: "5 minut",
    notes: "Chleb można podgrzać w tosterze lub na suchej patelni.",
    imgSrc: "./images/kanapki_z_miodem.jpg"
  },
  {
    name: 'Grillowane halloumi z warzywami',
    whichMeal: "śniadanie",
    kcal: 400,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'ser cypryjski "Halloumi"', amount: 100, unit: 'g'},
      {ingrName: 'ogórek kiszony', amount: 1, unit: 'sztuka'},
      {ingrName: 'pomidor', amount: 1, unit: 'sztuka'},
      {ingrName: 'mix sałat/rukola', amount: 1, unit: 'garść'},
      {ingrName: 'rzodkiewki', amount: 2, unit: 'sztuki'},
      {ingrName: 'sos winegret', amount: 1, unit: 'łyżka'},
    ],
    steps: [
      "Ser ugrillować/usmażyć z dwóch stron na suchej patelni (mały ogień), nie odrywaj na siłę - poczekaj, aż ser się zarumieni i lekko odejdzie od patelni (można zrobić to na patelni grillowej, grillu elektrycznym lub gazowym).",
      "Podawać z surówką ze świeżych warzyw polanych sosem."
    ],
    time: "15 minut",
    notes: "",
    imgSrc: "./images/grillowane_halloumi_z_warzywami.jpg"
  },
  {
    name: 'Koktajl bananowy z twarogiem',
    whichMeal: "drugie śniadanie",
    kcal: 290,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'banan', amount: 1, unit: 'sztuka'},
      {ingrName: 'jogurt naturalny', amount: 200, unit: 'g'},
      {ingrName: 'migdały (płatki)', amount: 2, unit: 'łyżki', gram: 30},
      {ingrName: 'miód', amount: 1, unit: 'łyżka', gram: 20},
      {ingrName: 'twaróg półtłusty', amount: "1/2", unit: 'kostki', gram: 100},
    ],
    steps: [
      "Wszystkie składniki umieścić w naczyniu miksującym, zmiksować [45 s / obr. 10]."
    ],
    time: "5 minut",
    notes: "2 porcje",
    imgSrc: "./images/koktajl_bananowy_z_twarogiem.jpg"
  },
  {
    name: 'Wege burger z fasoli',
    whichMeal: "obiad",
    kcal: 410,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'czosnek', amount: 1, unit: 'mały ząbek'},
      {ingrName: 'cebula', amount: "1/2", unit: 'sztuki', gram: "50-60"},
      {ingrName: 'płatki owsiane', amount: 25, unit: 'g'},
      {ingrName: 'fasola czerwona/czarna z puszki', amount: 120, unit: 'g'},
      {ingrName: 'chili mielone', amount: 1, unit: 'szczypta'},
      {ingrName: 'kmin rzymski', amount: "1/2", unit: 'łyżeczki'},
      {ingrName: 'sól', amount: "1/2", unit: 'łyżeczki'},
      {ingrName: 'pieprz', amount: 1, unit: 'szczypta'},
      {ingrName: 'oliwa z oliwek', amount: 1, unit: 'łyżka', gram: 10},
      {ingrName: 'bułka grahamka/pełnoziarnista', amount: 2, unit: 'sztuki'},
      {ingrName: 'sałata (np. rzymska/lodowa)'},
      {ingrName: 'czerwona cebula'},
      {ingrName: 'ogórek kiszony'},
      {ingrName: 'pomidor', amount: 2, unit: 'plastry'},
      {ingrName: 'ketchup'},
    ],
    steps: [
      "W naczyniu miksującym umieścić czosnek, cebulę oraz płatki owsiane, rozdrobnić [5 s / obr. 5]. Zgarnąć kopystką. Powtórzyć.",
      "Dodać fasolę, chili, kmin rzymski, sól i pieprz. Wymieszać [5 s / obr. wsteczne 4].",
      "Wilgotnymi dłońmi uformować 2 kotlety i wstawić do lodówki na 0,5-1 godzinę.",
      "Smażyć na oliwie, na średnim ogniu z obu stron.",
      "Bułkę można podpiec w tosterze lub w piekarniku (do zarumienienia).",
      "Na bułce ułożyć sałatę, burgera, dodać krążki czerwonej cebuli, ogórka kiszonego, pomidora i polać ketchupem."
    ],
    time: "25 minut + 0,5-1h chłodzenie",
    notes: "2 porcje",
    imgSrc: "./images/wege_burger_z_fasoli.jpg"
  },
  {
    name: 'Pieczona owsianka z malinami/truskawkami',
    whichMeal: "kolacja",
    kcal: 350,
    mom: 0,
    me: 2,
    ingredients: [
      {ingrName: 'jajko', amount: 1, unit: 'sztuka'},
      {ingrName: 'jogurt naturalny', amount: 1, unit: 'łyżka', gram: 20},
      {ingrName: 'maliny/truskawki (mrożone)', amount: 250, unit: 'g'},
      {ingrName: 'granat', amount: "1/4", unit: 'sztuki'},
      {ingrName: 'napój roślinny', amount: 80, unit: 'g'},
      {ingrName: 'płatki owsiane', amount: 80, unit: 'g'},
      {ingrName: 'miód', amount: 30, unit: 'g'},
      {ingrName: 'płatki migdałowe', amount: 2, unit: 'łyżki', gram: 20},
    ],
    steps: [
      "Wszystkie składniki wymieszać [15 s / obr. wsteczne 3], przełożyć do dwóch kokilek, posypać płatkami migdałów.",
      "Zapiekać 30-40 minut w 180&deg;C."
    ],
    time: "35-45 minut",
    notes: "2 porcje <br/> Masę można przygotować wcześniej.",
    imgSrc: "./images/pieczona_owsianka_z_malinami.jpg"
  },
  {
    name: 'Łosoś wędzony z sosem musztardowo-miodowym',
    whichMeal: "śniadanie",
    kcal: 380,
    mom: 1,
    me: 1,
    ingredients: [
      {ingrName: 'musztarda (np. DIJON)', amount: 3, unit: 'łyżeczki', gram: 30},
      {ingrName: 'miód', amount: 1, unit: 'łyżeczka', gram: 8},
      {ingrName: 'sok z cytryny', amount: 'kilka', unit: 'kropel'},
      {ingrName: 'oliwa z oliwek', amount: 1, unit: 'łyżka'},
      {ingrName: 'łosoś wędzony na zimno (lub inna wędzona ryba, np. makrela, pstrąg - ok. 160 kcal)', amount: 100, unit: 'g'},
      {ingrName: 'ogórek zielony/kiszony'},
      {ingrName: 'papryka czerwona', amount: "kawałek"},
      {ingrName: 'pomidorki koktajlowe', amount: 5, unit: 'sztuk'},
      {ingrName: 'rukola', amount: 1, unit: 'garść'},
      {ingrName: 'granat', amount: "1/4", unit: 'sztuki'},
    ],
    steps: [
      "W miseczce wymieszać musztardę, miód i sok z cytryny. Następnie intensywnie mieszając, dodawać powoli oliwę.",
      "Na talerzu ułożyć rukolę, wkroić ogórka i ułożyć pomidorki oraz kawałki ryby.",
      "Sałatkę polać sosem, posypać granatem."
    ],
    time: "10 minut",
    notes: "Dla mamy ryby tylko wędzone na gorąco, na zimno zbyt surowo smakuje.<br/> Dla mamy mniej musztardy.",
    imgSrc: "./images/losos_wedzony_z_sosem.jpg"
  },
  {
    name: 'Puszyste placuszki z owocami',
    whichMeal: "drugie śniadanie",
    kcal: 290,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'jajko', amount: 1, unit: 'sztuka'},
      {ingrName: 'mąka ryżowa', amount: 1, unit: 'łyżka', gram: 15},
      {ingrName: 'olej kokosowy', amount: 1, unit: 'łyżeczka', gram: 5},
      {ingrName: 'syrop klonowy', amount: 2, unit: 'łyżki', gram: 20},
      {ingrName: 'nektarynka (lub inne owoce)', amount: 1, unit: 'sztuka', gram: "100-150"},
    ],
    steps: [
      "Założyć motylek, do suchego naczynia miksującego wlać białko, ubijać ok. [2-3 min / obr. 3,5] lub do momentu, aż piana będzie sztywna.",
      "Zdjąć motylek, dodać żółtko i mąkę, wymieszać [10 s / obr. 3].",
      "Rozgrzać patelnię i dodać niewielką ilość oleju kokosowego. Uformować łyżką placuszki. Smażyć na małym ogniu.",
      "Placuszki polać syropem klonowym, podawać z owocami."
    ],
    time: "20 minut",
    notes: "Mąkę ryżową można otrzymać ze zmielenia ryżu [30-60 s / obr. 10].",
    imgSrc: "./images/puszyste_placuszki_z_owocami.jpg"
  },
  {
    name: 'Śledzie "w śmietanie"',
    whichMeal: "obiad",
    kcal: 420,
    mom: 0,
    me: 2,
    ingredients: [
      {ingrName: 'śledź w oleju', amount: 200, unit: 'g (po odsączeniu)'},
      {ingrName: 'cebula', amount: "1/2", unit: 'sztuki'},
      {ingrName: 'jabłko', amount: "2/3", unit: 'sztuki', gram: 100},
      {ingrName: 'jogurt naturalny, gęsty', amount: 4, unit: 'łyżki', gram: "80-100"},
      {ingrName: 'pieprz, papryka'},
      {ingrName: 'ziemniaki', amount: 4, unit: 'sztuki', gram: 360},
      {ingrName: 'koperek'},
      {ingrName: 'mleko do moczenia'},
    ],
    steps: [
      "Śledzie odsączyć z zalewy (można umyć, moczyć ok. 30 minut w mleku) i pokroić na kawałeczki.",
      "Cebulę rozdrobnić [3-4 s / obr. 5] lub pokroić w drobną kosteczkę, aby nie zrobiła się gorzka. Przełożyć do miski.",
      "Jabłko rozdrobnić [4-6 s / obr. 4], przełożyć do cebuli.",
      "Dodać śledzie, wymieszać z jogurtem, pieprzem i papryką.",
      "Wstawić do lodówki na min. 2h.",
      "Podawać z ziemniakami posypanymi koperkiem."
    ],
    time: "10 minut + 30 minut moczenie + 2h chłodzenie",
    notes: "2 porcje",
    imgSrc: "./images/sledzie_w_smietanie.jpg"
  },

  {
    name: 'Cukinia faszerowana kaszą jaglaną z papryką i ogórkiem',
    whichMeal: "kolacja",
    kcal: 330,
    mom: 1,
    me: 2,
    ingredients: [
      {ingrName: 'kasza jaglana', amount: "1/4", unit: 'szklanki', gram: 40},
      {ingrName: 'natka pietruszki', amount: "dużo"},
      {ingrName: 'papryka czerwona', amount: "1/3", unit: 'sztuki', gram: 100},
      {ingrName: 'ogórek kiszony/konserwowy', amount: 1, unit: 'sztuka', gram: 60},
      {ingrName: 'oliwa z oliwek', amount: 1, unit: 'łyżeczka', gram: 5},
      {ingrName: 'cukinia', amount: 1, unit: 'mała sztuka', gram: 250},
      {ingrName: 'parmezan tarty', amount: 1, unit: 'łyżka', gram: 12},
      {ingrName: 'sól, pieprz'},
    ],
    steps: [
      "Kaszę ugotować w połowie szklanki wody.",
      "Natkę rozdrobnić [3 s / obr. 8]. dodać paprykę i rozdrobnić [4 s / obr. 4] (lub pokroić w kosteczkę nożem), przełożyć do miseczki.",
      "Do naczynia miksującego włożyć ogórek, rozdrobnić [4-6 s / obr. 5] lub pokroić nożem.",
      "Dodać oliwę, kaszę, rozdrobnioną paprykę, sól i pieprz. Wymieszać [10 s / obr. wsteczne 2].",
      "Cukinię przekroić na pół, wydrążyć miąższ i nadziać farszem.",
      "Posypać serem. Zapiekać w piekarniku w 180&deg;C przez 20 minut (lub do czasu aż cukinia zmięknie)."
    ],
    time: "40 minut",
    notes: "",
    imgSrc: "./images/cukinia_faszerowana_kasza_jaglana.jpg"
  },
  {
    name: 'Omlet a\'la pizza',
    whichMeal: "śniadanie",
    kcal: 360,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'jajka', amount: 2, unit: 'sztuki'},
      {ingrName: 'bazylia, świeża', amount: "kilka", unit: 'listków'},
      {ingrName: 'ketchup', amount: 1, unit: 'łyżka', gram: 15},
      {ingrName: 'oliwki czarne', amount: 5, unit: 'sztuk'},
      {ingrName: 'oregano', amount: "1/3", unit: 'łyżeczki'},
      {ingrName: 'pieprz, sól', amount: 1, unit: 'szczypta'},
      {ingrName: 'rukola', amount: 1, unit: 'garść', gram: 20},
      {ingrName: 'ser mozzarella (kulka)', amount: "1/2", unit: 'sztuki', gram: 50},
      {ingrName: 'szynka', amount: 2, unit: 'plastry', gram: 30},
      {ingrName: 'masło klarowane', amount: 1, unit: 'łyżeczka', gram: 8},
      {ingrName: 'warzywa (np. pomidorki koktajlowe, papryka, ogórek kiszony)'},
    ],
    steps: [
      "Jajka umieścić w naczyniu miksującym, dodać sól, pieprz i oregano, wymieszać [20 s / obr. 3].",
      "Na patelni rozgrzać masło klarowane, wylać masę jajeczną.",
      "Przykryć pokrywką i zapiekać na niewielkim ogniu. Kiedy masa lekko się zetnie, dodać pokruszoną mozzarellę i kawałeczki szynki i dalej zapiekać pod przykryciem, aż masa zupełnie się zetnie.",
      "Omlet podawać posypany listkami bazylii, rukolą oraz z ketchupem w akompaniamencie ulubionych surowych warzyw."
    ],
    time: "15 minut",
    notes: "Jednorazowo można przyrządzić podwójną porcję.",
    imgSrc: "./images/omlet_ala_pizza.jpg"
  },
  {
    name: 'Babeczki "na szybko"',
    whichMeal: "drugie śniadanie",
    kcal: 315,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'jogurt grecki', amount: 200, unit: 'g'},
      {ingrName: 'jajka', amount: 2, unit: 'sztuki'},
      {ingrName: 'masło orzechowe', amount: 4, unit: 'łyżki', gram: 80},
      {ingrName: 'miód', amount: 3, unit: 'łyżki', gram: 75},
      {ingrName: 'ekstrakt wanilii', amount: 2, unit: 'łyżeczki'},
      {ingrName: 'płatki owsiane', amount: 160, unit: 'g'},
      {ingrName: 'mąka pełnoziarnista/orkiszowa/owsiana', amount: 50, unit: 'g'},
      {ingrName: 'proszek do pieczenia', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'soda oczyszczona', amount: "1/2", unit: 'łyżeczki'},
      {ingrName: 'sól', amount: "1/2", unit: 'łyżeczki'},
      {ingrName: 'cynamon', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'borówki/maliny/owoce leśne', amount: 3, unit: 'garści', gram: 150},
    ],
    steps: [
      "Nagrzać piekarnik do 215&deg;C.",
      "Blaszkę do pieczenia babeczek wyłożyć papilotkami.",
      "W naczyniu miksującym umieścić jogurt grecki, jajka, masło orzechowe, miód oraz ekstrakt waniliowy, wymieszać [10 s / obr. 3].",
      "W dużej misce wymieszać płatki owsiane, mąkę, proszek do pieczenia, sodę, sól oraz cynamon.",
      "Dodać do naczynia i wymieszać [10 s / obr. 4] (lub do całkowitego połączenia składników).",
      "Dodać borówki i przemieszać kopystką.",
      "Przełożyć łyżką ciasto do foremek na babeczki tak, aby ciasto sięgało do brzegów papilotek.",
      "Wstawić do piekarnika.",
      "Po 5 minutach pieczenia, zmniejszyć temperaturę do 180&deg;C i piec jeszcze przez około 14-16 minut.",
      "Upieczone babeczki będą bardzo miękkie, lecz po ostygnięciu stwardnieją."
    ],
    time: "35 minut",
    notes: "6 porcji",
    imgSrc: "./images/babeczki_na_szybko.jpg"
  },
  {
    name: 'Indyjski kurczak w jogurcie',
    whichMeal: "obiad",
    kcal: 390,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'ryż basmati/jaśminowy', amount: 160, unit: 'g'},
      {ingrName: 'cebula', amount: 1, unit: 'sztuka', gram: 100},
      {ingrName: 'czosnek', amount: 2, unit: 'ząbki'},
      {ingrName: 'imbir, korzeń', amount: 15, unit: 'g'},
      {ingrName: 'papryka chili zielona', amount: 1, unit: 'sztuka', gram: 20},
      {ingrName: 'kolendra, świeża'},
      {ingrName: 'oliwa z oliwek', amount: "1,5", unit: 'łyżki', gram: 15},
      {ingrName: 'kmin rzymski, kolendra', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'sól', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'kurkuma', amount: "1/2", unit: 'łyżeczki'},
      {ingrName: 'pierś z kurczaka lub udko wyfiletowane bez skóry', amount: 400, unit: 'g'},
      {ingrName: 'jogurt grecki', amount: 250, unit: 'g'},
      {ingrName: 'przecier pomidorowy (lub zmiksowane pomidory w puszce)', amount: 50, unit: 'g'},
    ],
    steps: [
      "W koszyczku umieścić ryż, ustawić [20 min / Varoma / obr. 4]. Ugotowany ryż odstawić w ciepłe miejsce, opróżnić naczynie.",
      "Do naczynia miksującego włożyć cebulę, czosnek, chili, imbir i kolendrę, rozdrobnić [5 s / obr. 5]. Zgarnąć kopystką.",
      "Dodać oliwę, zamiast miarki na pokrywę nałożyć koszyczek, ustawić [3 min / 120&deg;C / obr. \"kopystka\"].",
      "Dodać kumin, kolendrę, sól i kurkumę, dusić kolejne [3 min / 120&deg;C / obr. \"kopystka\"].",
      "Dodać kurczaka pokrojonego w kostkę, jogurt i przecier pomidorowy.",
      "Przemieszać kopystką, gotować [25-30 min / 100&deg;C / obr. wsteczne 1].",
      "Podawać z ryżem."
    ],
    time: "1h",
    notes: "4 porcje",
    imgSrc: "./images/indyjski_kurczak_w_jogurcie.jpg"
  },
  {
    name: 'Carpaccio z buraczkiem i z gruszką',
    whichMeal: "kolacja",
    kcal: 340,
    mom: null,
    me: 2,
    ingredients: [
      {ingrName: 'woda', amount: 500, unit: 'g'},
      {ingrName: 'burak', amount: 1, unit: 'sztuka', gram: 70},
      {ingrName: 'rukola', amount: 2, unit: 'garści'},
      {ingrName: 'ser pleśniowy błękitny lazur', amount: 30, unit: 'g'},
      {ingrName: 'gruszka', amount: "1/2", unit: 'sztuki'},
      {ingrName: 'sos winegret', amount: "1,5", unit: 'łyżki'},
      {ingrName: 'orzechy włoskie', amount: 2, unit: 'sztuki', gram: 10},
    ],
    steps: [
      "Do naczynia miksującego wlać wodę. Buraka pokroić w cienkie plasterki i włożyć do koszyczka. Gotować na parze [15-20 min / Varoma / obr.1].",
      "Na półmisku ułożyć: rukolę, kolejno plastry buraka, dodać pokruszony ser, ósemki gruszki i polać sosem winegret. Posypać orzechami."
    ],
    time: "30 minut",
    notes: "",
    imgSrc: "./images/carpaccio_z_buraczkiem_i_gruszka.jpg"
  },
  {
    name: 'Jogurt wege koko z musli i owocami',
    whichMeal: "śniadanie",
    kcal: 380,
    mom: null,
    me: 2,
    ingredients: [
      {ingrName: 'wegański jogurt kokosowy', amount: 1, unit: 'opakowanie', gram: 160},
      {ingrName: 'kiwi', amount: 1, unit: 'sztuka'},
      {ingrName: 'mandarynka', amount: 1, unit: 'sztuka', gram: 65},
      {ingrName: 'musli', amount: 2, unit: 'łyżki', gram: 25},
      {ingrName: 'orzechy włoskie', amount: 1, unit: 'łyżka', gram: 15},
    ],
    steps: [
      "W miseczce umieścić jogurt, podać pokrojone owoce, posypać musli i orzechami."
    ],
    time: "5 minut",
    notes: "",
    imgSrc: "./images/jogurt_wege_koko.jpg"
  },
  {
    name: 'Sałatka z winogronami i szynką parmeńską',
    whichMeal: "drugie śniadanie",
    kcal: 310,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'rukola', amount: 2, unit: 'garście'},
      {ingrName: 'winogrona', amount: 1, unit: 'garść', gram: 50},
      {ingrName: 'szynka parmeńska', amount: 2, unit: 'plastry', gram: 30},
      {ingrName: 'ser gorgonzola', amount: 30, unit: 'g'},
      {ingrName: 'orzechy włoskie', amount: 1, unit: 'łyżka', gram: 10},
      {ingrName: 'miód', amount: "1/2", unit: 'łyżeczki', gram: 4},
      {ingrName: 'oliwa z oliwek', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'sok z cytryny', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'sól, pieprz'},
    ],
    steps: [
      "Na talerzu ułożyć sałatę, dodać pokrojone na połówki winogrona.",
      "Dodać szynkę pokrojoną na kawałki i pokrojony w kosteczkę ser.",
      "Posypać orzechami i polać słodkim winegretem (w miseczce wymieszać oliwę, sok z cytryny i miód).",
      "Posypać świeżo zmielonym pieprzem i solą."
    ],
    time: "5 minut",
    notes: "",
    imgSrc: "./images/salatka_z_winogronami_i_szynka.jpg"
  },
  {
    name: 'Hawajskie szaszłyki z sosem salsa',
    whichMeal: "obiad",
    kcal: 380,
    mom: null,
    me: 1,
    ingredients: [
      {ingrName: 'jogurt naturalny', amount: 50, unit: 'g'},
      {ingrName: 'oliwa z oliwek', amount: 1, unit: 'łyżka'},
      {ingrName: 'curry, kurkuma, papryka słodka', amount: "po 1/2", unit: 'łyżeczki'},
      {ingrName: 'filet z piersi kurczaka', amount: 300, unit: 'g'},
      {ingrName: 'ananas', amount: 200, unit: 'g'},
      {ingrName: 'papryka czerwona', amount: 1, unit: 'sztuka'},
      {ingrName: 'szalotka', amount: 2, unit: 'sztuki', gram: 40},
      {ingrName: 'papryka zielona', amount: "1/4", unit: 'sztuki', gram: 40},
      {ingrName: 'papryka jalapeno w zalewie, marynowana', amount: 2, unit: 'łyżki', gram: 30},
      {ingrName: 'pomidory w puszce', amount: 400, unit: 'g'},
      {ingrName: 'sól, pieprz'},
      {ingrName: 'erytrol', amount: 2, unit: 'łyżki'},
      {ingrName: 'ocet', amount: 3, unit: 'łyżki'},
      {ingrName: 'czosnek granulowany', amount: "2/3", unit: 'łyżeczki'},
      {ingrName: 'mąka ziemniaczana', amount: 1, unit: 'łyżeczka'},
    ],
    steps: [
      "Jogurt, oliwę, curry, kurkumę i paprykę słodką przełożyć do naczynia miksującego i wymieszać [10 s / obr. 3].",
      "Pierś z kurczaka pokroić w 2-3cm kostkę, dodać do marynaty i wymieszać [10 s / obr. wsteczne 2,5]. Marynować w lodówce pół godziny (a najlepiej całą noc).",
      "Na szpikulce do szaszłyków nabijać na przemian mięso, ananas, papryka.",
      "Piec na mocno rozgrzanym grillu obracając szaszłyki (10-15 minut) lub w piekarniku (ok. 20 minut, 180&deg;C).",
      "SOS SALSA: W naczyniu miksującym umieścić szalotkę, rozdrobnić [5 s/ obr. 5]. Przełożyć do innego naczynia.",
      "Dodać zieloną paprykę, jalapeno, rozdrobnić [5 s/ obr. 5].",
      "Dodać puszkę pomidorów, szczyptę soli i pieprzu, czosnek granulowany, erytrol oraz ocet. Gotować przez [15 min / 100&deg'C / obr. 1].",
      "Dodać szalotkę i gotować jeszcze przez ok. [2 min / 100&deg;C / obr. 1].",
      "Dodać mąkę ziemniaczaną, gotować [2 min / 100&deg;C / obr. wsteczne 2].",
      "Odstawić do ostudzenia, przechowywać w lodówce."
    ],
    time: "10 minut + marynowanie (30 minut lub całą noc) + 35 minut + sos (25 minut)",
    notes: "2 porcje szaszłyków <br/> 4 porcje sosu salsa <br/> Zamiast sosu salsa można użyć innego sosu (kupnego) na bazie pomidorów np. słodko-kwaśny chili lub salsa do nachos (2-3 łyżki) - byle nie majonezowy.",
    imgSrc: "./images/hawajskie_szaszlyki.jpg"
  },
  {
    name: 'Tosty z burratą i pomidorami',
    whichMeal: "kolacja",
    kcal: 370,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'chleb żytni', amount: 2, unit: 'kromki'},
      {ingrName: 'oliwa z oliwek', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'pomidor', amount: "1/2", unit: 'sztuki'},
      {ingrName: 'ser burrata', amount: "1/2", unit: 'sztuki', gram: 60},
      {ingrName: 'sól, pieprz'},
      {ingrName: 'przyprawa - suszone pomidory z czosnkiem i bazylią (opcjonalnie)'},
    ],
    steps: [
      "Chleb podgrzać w tosterze, posmarować burratą.",
      "Ułożyć plastry pomidora, skropić oliwą, doprawić solą, świeżo zmielonym kolorowym pieprzem oraz opcjonalnie przyprawą."
    ],
    time: "5 minut",
    notes: "",
    imgSrc: "./images/tosty_z_burrata_i_pomidorami.jpg"
  },
  {
    name: 'Kiełbasa z chrzanem i sałatką z surowych warzyw',
    whichMeal: "śniadanie",
    kcal: 370,
    mom: 2,
    me: 1,
    ingredients: [
      {ingrName: 'kiełbasa (np. biała surowa/parówkowa/wędzona - z dużą zawartością mięsa)', amount: 1, unit: 'sztuka', gram: "100-120"},
      {ingrName: 'liść laurowy, ziele angielskie (jeśli kiełbasa biała)'},
      {ingrName: 'chrzan', amount: 2, unit: 'łyżeczki'},
      {ingrName: 'warzywa (np. ogórek kiszony, papryka żółta, pomidor, kiełki'},
    ],
    steps: [
      "Białą kiełbasę zagotować w wodzie z liściem laurowym i zielem angielskim (jeśli kiełbasa inna niż biała surowa, to liść i ziele pominąć).",
      "Podawać z chrzanem i ulubionymi surowymi warzywami."
    ],
    time: "20 minut",
    notes: "Kaloryczność kiełbasy powinna odpowiadać max 300 kcal.",
    imgSrc: "./images/kielbasa_z_chrzanem_i_salatka.jpg"
  },
  {
    name: 'Sałatka pomarańczowa z miętą i pistacjami',
    whichMeal: "drugie śnidanie",
    kcal: 350,
    mom: null,
    me: 2,
    ingredients: [
      {ingrName: 'jogurt naturalny', amount: 150, unit: 'g'},
      {ingrName: 'mięta świeża', amount: "kilka", unit: 'listków'},
      {ingrName: 'pistacje prażone, niesolone', amount: 1, unit: 'łyżka', gram: 20},
      {ingrName: 'pomarańcza', amount: 1, unit: 'sztuka'},
    ],
    steps: [
      "W naczyniu miksującym umieścić listki mięty, rozdrobnić [5 s/ obr. 8], zgarnąć kopystką.",
      "Dodać jogurt, obraną i pokrojoną w kostkę pomarańczę, wymieszać [10 s / obr. wsteczne 1,5].",
      "Przełożyć do miseczki i posypać pokruszonymi pistacjami."
    ],
    time: "5 minut",
    notes: "",
    imgSrc: "./images/salatka_pomaranczowa_z_mieta_i_pistacjami.jpg"
  },
  {
    name: 'Indyjska zupa Dahl',
    whichMeal: "obiad",
    kcal: 410,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'cebula', amount: 1, unit: 'nieduża sztuka', gram: 60},
      {ingrName: 'czosnek', amount: 2, unit: 'ząbki'},
      {ingrName: 'masło klarowane', amount: 2, unit: 'łyżki', gram: 30},
      {ingrName: 'soczewica czerwona sucha', amount: "3/4", unit: 'szklanki', gram: 150},
      {ingrName: 'bulion rosołowy', amount: 350, unit: 'g'},
      {ingrName: 'przyprawy: garam masala, imbir suszony, kurkuma', amount: "po 2/3", unit: 'łyżeczki'},
      {ingrName: 'chili', amount: "1/2", unit: 'łyżeczki'},
      {ingrName: 'mleczko kokosowe', amount: 250, unit: 'g'},
      {ingrName: 'pomidory w puszce (lub świeże bez skórki)', amount: 400, unit: 'g'},
      {ingrName: 'erytrol', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'sok z cytryny', amount: 1, unit: 'łyżka'},
      {ingrName: 'świeża kolendra lub pietruszka'},
      {ingrName: 'chleb żytni', amount: 4, unit: 'kromki (1 na porcję)'},
    ],
    steps: [
      "W naczyniu miksującym umieścić cebulę i czosnek. Rozdrobnić [5 s / obr. 5]. Zgarnąć kopystką.",
      "Dodać 1 łyżkę masła (15g) i dusić [3 min / 120&deg;C / obr. 1].",
      "Dodać suchą soczewicę oraz bulion i gotować [15-20 minut / 100&deg'C / obr. 'kopystką'].",
      "W tym czasie na patelni rozgrzać 1 łyżkę masła (15g), dodać przyprawy o podpiekać przez 1-2 minuty ciągle mieszając, aby przyprawy się nie przypaliły. Ściągnąć z ognia.",
      "Do ugotowanej soczewicy dodać mleczko kokosowe, pomidory, erytrol, sok z cytryny oraz przygotowaną 'zacierkę' z przypraw, wymieszać [10 s / obr. wsteczne 2]. Posolić do smaku.",
      "Gotować jeszcze [3 min / 100&deg;C / obr. 'kopystką'].",
      "Podawać z posiekaną kolendrą lub pietruszką i grzanką z chleba."
    ],
    time: "30 minut",
    notes: "4 porcje",
    imgSrc: "./images/indyjska_zupa_dahl.jpg"
  },
  {
    name: 'Sałatka meksykańska',
    whichMeal: "kolacja",
    kcal: 300,
    mom: null,
    me: 1,
    ingredients: [
      {ingrName: 'por', amount: "1/2", unit: 'sztuki', gram: 70},
      {ingrName: 'kukurydza konserwowa', amount: 100, unit: 'g'},
      {ingrName: 'ananas', amount: 240, unit: 'g'},
      {ingrName: 'papryka czerwona', amount: "1/3", unit: 'sztuki', gram: 100},
      {ingrName: 'ser żółty', amount: 100, unit: 'g'},
      {ingrName: 'fasola kidney, konserwowa', amount: 1, unit: 'mini puszka', gram: 120},
      {ingrName: 'majonez', amount: 1, unit: 'łyżka', gram: 25},
      {ingrName: 'sól, pieprz'},
    ],
    steps: [
      "Pora przekroić wzdłuż na cienkie paski (na około) i posiekać, przełożyć do miski.",
      "Dodać kukurydzę, pokrojone w kostkę: ananasa, paprykę i ser.",
      "Dodać odsączoną fasolę.",
      "Dodać majonez, doprawić solą i pieprzem. Wymieszać."
    ],
    time: "15 minut",
    notes: "3 porcje",
    imgSrc: "./images/salatka_meksykanska.jpg"
  },
  {
    name: 'Wrap z tuńczykiem',
    whichMeal: "śniadanie",
    kcal: 410,
    mom: null,
    me: 1,
    ingredients: [
      {ingrName: 'papryka czerwona', unit: 'kawałek', gram: 50},
      {ingrName: 'ogórek konserwowy', amount: 1, unit: 'sztuka'},
      {ingrName: 'tuńczyk w sosie własnym', amount: 1, unit: 'puszka "mini"', gram: "80-100"},
      {ingrName: 'szczypiorek', amount: 1, unit: 'łyżka'},
      {ingrName: 'kukurydza konserwowa', amount: 2, unit: 'łyżki', gram: 50},
      {ingrName: 'jogurt naturalny', amount: 1, unit: 'łyżka', gram: 15},
      {ingrName: 'musztarda', amount: 1, unit: 'łyżka', gram: 15},
      {ingrName: 'sól, pieprz'},
      {ingrName: 'tortilla pełnoziarnista', amount: 1, unit: 'sztuka'},
      {ingrName: 'sałata', amount: "2-3", unit: 'liście'},
    ],
    steps: [
      "W naczyniu miksującym umieścić paprykę i ogórka, rozdrobnić [3 s / obr. 4].",
      "Dodać odsączonego z zalewy tuńczyka, posiekany szczypiorek, kukurydzę, jogurt, musztardę oraz sól i pieprz, wymieszać [15 s / obr. wsteczne 3].",
      "Tortillę lekko podgrzać na suchej patelni, ułożyć pastę z tuńczyka oraz sałatę.",
      "Tortillę zwinąć w rulon i przekroić na pół."
    ],
    time: "10 minut",
    notes: "",
    imgSrc: "./images/wrap_z_tunczykiem.jpg"
  },
  {
    name: 'Banan z orzechami',
    whichMeal: "drugie śniadanie",
    kcal: 260,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'banan', amount: 1, unit: 'sztuka'},
      {ingrName: 'orzechy (np. macadamia)', amount: 5, unit: 'sztuk', gram: 20},
    ],
    steps: [
      "Zjeść."
    ],
    time: "2 minut",
    notes: "",
    imgSrc: "./images/banan_z_orzechami.jpg"
  },
  {
    name: 'Jajka sadzone z mizerią i ziemniakami',
    whichMeal: "obiad",
    kcal: 420,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'ogórek gruntowy', amount: "1-2", unit: 'sztuki', gram: 100},
      {ingrName: 'szczypiorek'},
      {ingrName: 'sok z cytryny', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'jogurt grecki', amount: 3, unit: 'łyżki', gram: 50},
      {ingrName: 'sól, pieprz'},
      {ingrName: 'erytrol (opcjonalnie)', unit: 'odrobina'},
      {ingrName: 'masło klarowane', amount: 1, unit: 'łyżka', gram: 10},
      {ingrName: 'jajka', amount: 2, unit: 'sztuki'},
      {ingrName: 'ziemniaki', amount: 2, unit: 'sztuki', gram: 180},
      {ingrName: 'koperek'},
    ],
    steps: [
      "Ugotować ziemniaki.",
      "Ogórki pokroić na cienkie plasterki, szczypiorek posiekać. Doprawić, dodać jogurt i sok z cytryny. Wymieszać.",
      "Na patelni rozgrzać masło klarowane, wbić jajka, doprawić solą i świeżo zmielonym kolorowym pieprzem.",
      "Smażyć, aż białko się zetnie (żółtko ma być płynne).",
      "Jajka sadzone podawać z mizerią i ziemniakami posypanymi koperkiem."
    ],
    time: "30 minut",
    notes: "",
    imgSrc: "./images/jajka_sadzone_z_mizeria.jpg"
  },
  {
    name: 'Sałatka Caprese',
    whichMeal: "kolacja",
    kcal: 320,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'rukola', amount: 1, unit: 'spora garść'},
      {ingrName: 'pomidor', amount: 1, unit: 'sztuka'},
      {ingrName: 'ser mozzarella (kulka)', amount: 100, unit: 'g'},
      {ingrName: 'bazylia, świeża/suszona'},
      {ingrName: 'kapary', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'oliwa z oliwek', amount: 1, unit: 'łyżeczka'},
    ],
    steps: [
      "Na talerzu ułożyć rukolę.",
      "Pomidora i mozzarellę pokroić w plastry i układać na przemian.",
      "Całość posypać listkami bazylii (lub użyć suszonej) oraz kaparami, pokropić oliwą, oprószyć solą i pieprzem."
    ],
    time: "5 minut",
    notes: "",
    imgSrc: "./images/salatka_caprese.jpg"
  },
  {
    name: 'Jajko poché z łososiem i fit sosem a\'la holenderskim',
    whichMeal: "śniadanie",
    kcal: 400,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'jajko', amount: 1, unit: 'sztuka'},
      {ingrName: 'chleb żytni', amount: 2, unit: 'kromki'},
      {ingrName: 'rukola/szpinak'},
      {ingrName: 'łosoś wędzony na zimno, plastry', amount: 50, unit: 'g'},
      {ingrName: 'jogurt grecki', amount: 1, unit: 'łyżka', gram: 25},
      {ingrName: 'musztarda', amount: "1/2", unit: 'łyżeczki', gram: 5},
      {ingrName: 'majonez light', amount: 1, unit: 'łyżka', gram: 20},
      {ingrName: 'szczypiorek', amount: 1, unit: 'łyżka'},
    ],
    steps: [
      "Miarkę wyłożyć folią spożywczą, wbić do środka jajko, doprawić solą i pieprzem. Związać sakiewkę za pomocą nici.",
      "Sakiewkę z jajkiem ułożyć w dolnej części przystawki Varoma, wlać 500g wody, gotować na parze [10-11 min / Varoma / obr. 2]. Jeżeli po tym czasie jajko nie będzie gotowe (białko powinno być ścięte, a żółtko półpłynne), należy gotować na parze kolejne [2 min / Varoma / obr. 2].",
      "Chleb upiec w tosterze.",
      "W miseczce wymieszać jogurt, musztardę i majonez, doprawić solą i pieprzem.",
      "Na grzance ułożyć rukolę, łososia, na to jajko w koszulce, polać sosem, posypać szczypiorkiem i przykryć drugą grzanką."
    ],
    time: "20 minut",
    notes: "Można zamiast jajka w koszulce przyrządzić po prostu jajko sadzone (z minimalną ilością tłuszczu, żeby nie podbijać kaloryczności; 1 łyżka oliwy = 90 kcal).",
    imgSrc: "./images/jajko_poche_z_lososiem.jpg"
  },
  {
    name: 'Kakaowy pudding chia z truskawkami',
    whichMeal: "drugie śniadanie",
    kcal: 260,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'wiórki kokosowe', amount: 2, unit: 'łyżki', gram: 12},
      {ingrName: 'kakao', amount: 1, unit: 'łyżka', gram: 10},
      {ingrName: 'miód', amount: 1, unit: 'czubata łyżeczka', gram: 15},
      {ingrName: 'truskawki mrożone', amount: 1, unit: 'szklanka', gram: 160},
      {ingrName: 'nasiona chia', amount: 4, unit: 'łyżki', gram: 40},
      {ingrName: 'napój roślinny (np. kokosowy, mleko migdałowe itp.)', amount: 300, unit: 'g'},
    ],
    steps: [
      "Do naczynia miksującego wlać napój roślinny, dodać chia, kakao i miód. Wymieszać [2 min 20 s / obr. 3]. Przelać do szklanek, odstawić do lodówki na 3 godziny (lub na całą noc).",
      "Do czystego naczynia miksującego włożyć truskawki, zmiksować [20 s / obr. 6] (można dodać 1 łyżeczkę erytrolu do smaku). Przelać na pudding, podawać schłodzone."
    ],
    time: "5 minut + chłodzenie (min. 3h) + 5 minut",
    notes: "2 porcje <br/> Przygotować minimum 3-4 godziny wcześniej!!!",
    imgSrc: "./images/kakaowy_pudding_chia.jpg"
  },
  {
    name: 'Gołąbki w sosie pomidorowym',
    whichMeal: "obiad",
    kcal: 420,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'kapusta biała, młoda/włoska/stożkowa', amount: "8-10", unit: 'dużych liści'},
      {ingrName: 'cebula', amount: 1, unit: 'sztuka', gram: "100-120"},
      {ingrName: 'czosnek', amount: 2, unit: 'ząbki'},
      {ingrName: 'masło lub oliwa', amount: 1, unit: 'łyżka'},
      {ingrName: 'mielone z szynki/łopatki', amount: "500-600", unit: 'g'},
      {ingrName: 'sól, pieprz, majeranek, bazylia, oregano, słodka papryka'},
      {ingrName: 'jajko', amount: 1, unit: 'sztuka'},
      {ingrName: 'cebula (do sosu)', amount: 1, unit: 'sztuka', gram: 100},
      {ingrName: 'masło klarowane', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'koncentrat pomidorowy 30%', amount: 4, unit: 'łyżeczki'},
      {ingrName: 'passata pomidorowa (przecier)', amount: "200-250", unit: 'g'},
      {ingrName: 'koperek świeży'},
      {ingrName: 'ziemniaki', amount: 8, unit: 'sztuk (2 na porcję)', gram: 800},
    ],
    steps: [
      "W dużym garnku umieścić kapustę, zalać wodą, zagotować i gotować ok. 10-15 minut.",
      "Wodę z gotowania kapusty zachować. Wyjąć kapustę, oddzielić duże liście, usunąć twarde nasady.",
      "Do naczynia miksującego włożyć cebulę i czosnek, rozdrobnić [5 s / obr. 5], dusić na maśle [3 min / 120&deg;C / obr. 1].",
      "Dodać mięso, doprawić przyprawami, dodać jajko i wymieszać z kopystką [30 s / obr. wsteczne 4].",
      "Farsz zawinąć w liście kapusty i ułożyć na przystawce Varoma.",
      "Cebulę zeszklić na 1 łyżeczce masła klarowanego [3 min / 120&deg;C / ob. 1]",
      "Dodać 250g wody z gotowania kapusty, dodać koncentrat pomidorowy, pomidory lub przecier, sól i pieprz.",
      "Nałożyć przystawkę Varoma z gołąbkami i gotować [40 min / Varoma / obr. 1]. Gdyby po tym czasie sos był rzadki, można dusić (bez miarki) jeszcze [10 min / 110&deg;C / obr. 2].",
      "Na koniec dodać łyżkę jogurtu naturalnego, można doprawić solą i pieprzem, zamieszać [10 s / obr. 4].",
      "Gołąbki podawać z młodymi ziemniaczkami i sosem. Posypać dużą ilością posiekanego koperku."
    ],
    time: " minut",
    notes: "4 porcje <br/> Jeśli sos wyjdzie zbyt rzadki, można zagęścić go 1 łyżką mąki z ciecierzycy lub owsianej.",
    imgSrc: "./images/golabki_w_sosie_pomidorowym.jpg"
  },
  {
    name: 'Grillowane pieczarki nadziewane serami z papryczką chili',
    whichMeal: "kolacja",
    kcal: 325,
    mom: null,
    me: null,
    ingredients: [
      {ingrName: 'ser parmezan', amount: 30, unit: 'g (czy 50???)'},
      {ingrName: 'pieczarki', amount: "6-8", unit: 'dużych sztuk', gram: 600},
      {ingrName: 'papryka chili', amount: "1/2", unit: 'sztuki', gram: 10},
      {ingrName: 'czosnek', amount: 1, unit: 'ząbek'},
      {ingrName: 'cebula', amount: "1/4", unit: 'sztuki', gram: 30},
      {ingrName: 'natka pietruszki', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'serek śmietankowy Almette', amount: 50, unit: 'g'},
      {ingrName: 'ser żółty (np. cheddar)', amount: 60, unit: 'g'},
    ],
    steps: [
      "Do naczynia miksującego włożyć parmezan, rozdrobnić [10 s / obr. 10]. Przełożyć do innego naczynia, odstawić.",
      "Od pieczarek oddzielić nóżki, zachować. Kapelusze odstawić. Do naczynia miksującego włożyć nóżki pieczarek, papryczkę chili, czosnek, cebulę i natkę pietruszki, rozdrobnić [5 s / obr. 6]. Zgarnąć ze ścianek.",
      "Dodać 40g rozdrobnionego parmezanu, serek kremowy, ser cheddar i pieprz, rozdrobnić [5 s / obr. 6].",
      "Powstałym nadzieniem wypełniać pieczarki, posypać pozostałym rozdrobnionym parmezanem.",
      "Pieczarki piec 15-20 minut w piekarniku w 220&deg;C lub grillować 10-15 minut (lub do momentu, aż pieczarki nabiorą złotobrązowego koloru, a ser się rozpuści)."
    ],
    time: " minut",
    notes: "2 porcje <br/> Dość ciężkie jak na kolację.",
    imgSrc: "./images/grillowane_pieczarki_nadziewane_serami.jpg"
  },
  {
    name: 'Owsianka banoffee',
    whichMeal: "śniadanie",
    kcal: 380,
    mom: 1,
    me: 2,
    ingredients: [
      {ingrName: 'banan', amount: "1/2", unit: 'sztuki', gram: 60},
      {ingrName: 'jogurt naturalny', amount: 3, unit: 'łyżki', gram: 60},
      {ingrName: 'płatki owsiane', amount: 4, unit: 'łyżki', gram: 40},
      {ingrName: 'migdały, płatki', amount: 1, unit: 'łyżka', gram: 10},
      {ingrName: 'pudding proteinowy o smaku słony karmel Go Avtive', amount: "1/2", unit: 'opakowania', gram: 100},
    ],
    steps: [
      "W naczyniu miksującym umieścić płatki owsiane, dodać 100g wody, gotować 5 minut/ 95°C/ obr. wsteczne 1.",
      "Dodać jogurt, wymieszać 10 s/ obr. wsteczne 1,5.",
      "Banana pokroić w plasterki. W słoiczku lub salaterce umieścić na dnie kilka piastrów banana, na to płatki owsiane z jogurtem i pudding.","Wierzch posypać płatkami migdałów."
    ],
    time: "10 minut",
    notes: "",
    imgSrc: "./images/owsianka_banoffee.jpg"
  },
  {
    name: 'Sałatka z kozim serkiem, mandarynką i żurawiną',
    whichMeal: "drugie śniadanie",
    kcal: 340,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'orzechy włoskie', amount: 1, unit: 'łyżka', gram: 10},
      {ingrName: 'mandarynka', amount: 1, unit: 'sztuka'},
      {ingrName: 'ser kozi, miękki (krążki)', amount: 40, unit: 'g'},
      {ingrName: 'sałata lodowa, rukola', amount: "kilka", unit: 'liści'},
      {ingrName: 'żurawina suszona', amount: 1, unit: 'łyżka', gram: 20},
      {ingrName: 'sok z cytryny', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'musztarda', amount: "1/2", unit: 'łyżeczki'},
      {ingrName: 'oliwa z oliwek', amount: 1, unit: 'łyżeczka'},
    ],
    steps: [
      "Żurawinę zalać wrzątkiem i odstawić do namoczenia.",
      "Na talerzu ułożyć sałaty, dodać pokruszony ser, ząbki mandarynki.",
      "Dodać odsączoną żurawinę i pokruszone orzechy.",
      "Wymieszać składniki sosu (miód, musztarda, sok z cytryny, oliwa) i polać na sałatkę."
    ],
    time: "10 minut",
    notes: "",
    imgSrc: "./images/salatka_z_kozim_serkiem.jpg"
  },
  {
    name: 'Meksykańska zupa z kurczakiem',
    whichMeal: "obiad",
    kcal: 370,
    mom: 2,
    me: 2,
    ingredients: [
      {ingrName: 'batat', amount: 1, unit: 'sztuka', gram: 300},
      {ingrName: 'filet z piersi kurczaka', amount: 300, unit: 'g'},
      {ingrName: 'czosnek', amount: 2, unit: 'ząbki', gram: 10},
      {ingrName: 'cebula', amount: 1, unit: 'sztuka', gram: 80},
      {ingrName: 'oliwa z oliwek', amount: "2,5", unit: 'łyżki', gram: 25},
      {ingrName: 'soczewica czerwona, nasiona suche', amount: "1/3", unit: 'szklanki', gram: 60},
      {ingrName: 'kmin rzymski, słodka papryka, ostra papryka, kurkuma, suszone oregano, kolendra mielona, sól, pieprz', amount: "po 1/2", unit: 'łyżeczki'},
      {ingrName: 'bulion rosołowy', amount: 1, unit: 'litr'},
      {ingrName: 'śmietana 18%', amount: 100, unit: 'g'},
      {ingrName: 'chleb żytni', amount: 2, unit: 'kromki'},
      {ingrName: 'sok z limonki'},
      {ingrName: 'świeża kolendra lub natka pieruszki'},
    ],
    steps: [
      "Batata i pierś z kurczaka pokroić w kosteczkę.",
      "W naczyniu umieścić czosnek, rozdrobnić [3 s / obr. 8], dodać cebulę, rozdrobnić 5 s/ obr. 5.",
      "Dodać 15g oliwy i batata, dusić [5 min / 120°C / obr. wsteczne 1].",
      "Dodać suchą, przepłukaną soczewicę oraz kmin rzymski, słodką i ostrą paprykę, kurkumę, oregano i kolendrę, dusić [1 min / 120°C / obr. wsteczne 1].",
      "Jeżeli posiadasz osłonę noża miksującego, przełóż zawartość do miski, umieść w naczyniu miksującym osłonę noża i z powrotem przełóż wszystko do naczynia.",
      "Dodać gorący bulion, gotować [5 min/ 100°C/ obr. wsteczne 1].",
      "Dodać pokrojonego kurczaka, doprawić pieprzem i w razie potrzeby solą.",
      "Gotować [15 min/ 100°C/ obr. wsteczne 1].",
      "W tym czasie rozgrzać piekarnik do 200°C, chleb pokroić w kosteczkę, skropić oliwą, posypać przyprawami, upiec grzanki (3-4 minuty).",
      "Wyciągnąć osłonę noża, dodać śmietanę i wymieszać [10 s/ obr. wsteczne 1,5].",
      "Podawać z posiekaną kolendrą lub natką pietruszki oraz z grzankami. Można skropić sokiem z limonki."
    ],
    time: "40 minut",
    notes: "4 porcje",
    imgSrc: "./images/meksykańska_zupa_z_kurczakiem.jpg"
  },
  {
    name: 'Szybka pizza na spodzie z tortilli',
    whichMeal: "kolacja",
    kcal: 360,
    mom: null,
    me: null,
    ingredients: [
      {ingrName: 'tortilla wieloziarnista', amount: 2, unit: 'sztuki (1 na porcję)'},
      {ingrName: 'koncentrat pomidorowy', amount: 3, unit: 'łyżeczki'},
      {ingrName: 'zioła prowansalskie', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'sól, pieprz'},
      {ingrName: 'mozzarella, kulka', amount: 60, unit: 'g'},
      {ingrName: 'papryka chili', amount: "kawałek", gram: "5-10"},
      {ingrName: 'szynka parmeńska/szwardzwaldzka', amount: 6, unit: 'plastrów', gram: 90},
      {ingrName: 'pomidorki koktajlowe', amount: 8, unit: 'sztuk'},
      {ingrName: 'oliwki czarne lub zielone', amount: 10, unit: 'sztuk', gram: 30},
      {ingrName: 'rukola', amount: 2, unit: 'garście'},
    ],
    steps: [
      "Na suchej patelni podpiec placek z tortilli, przerzucić na drugą stronę. Placek posmarować sosem pomidorowym (wymieszać koncentrat pomidorowy, 3 łyżki wody, zioła prowansalskie sól i pieprz).",
      "Ułożyć plastry mozzarelli (można utrzeć i posypać), ułożyć plastry szynki, połówki pomidorków i oliwki (można dodać cienkie plasterki chili).",
      "Pizzę podpiekać na patelni, na małym ogniu, pod przykryciem do czasu, aż ser się roztopi (można również piec w piekarniku- 180 stopni, ok 5 minut).",
      "Po upieczeniu obłożyć rukolą."
    ],
    time: "15 minut (1 porcja)",
    notes: "2 porcje",
    imgSrc: "./images/szybka_pizza_na_spodzie_z_tortilli.jpg"
  },
  {
    name: 'Pasta z koziego serka z suszonymi pomidorami',
    whichMeal: "śniadanie",
    kcal: 420,
    mom: null,
    me: null,
    ingredients: [
      {ingrName: 'rukola', amount: 1, unit: 'mała garść'},
      {ingrName: 'morele suszone', amount: 30, unit: 'g'},
      {ingrName: 'pomidory suszone w oleju', amount: 40, unit: 'g'},
      {ingrName: 'ser kozi, miękki', amount: 120, unit: 'g'},
      {ingrName: 'miód', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'sól, pieprz'},
      {ingrName: 'chleb żytni razowy', amount: 2, unit: 'kromki (1 na porcję)'},
      {ingrName: 'surowe warzywa (np. pomidor, papryka, ogórek)'},
    ],
    steps: [
      "W naczyniu umieścić rukolę, rozdrobnić [3 s/ obr. 8].",
      "Dodać morele (jeśli są twarde, to uprzednio można namoczyć) i suszone pomidory, rozdrobnić [3 s/ obr. 8].",
      "Dodać serek kozi, miód, po szczypcie soli i pieprzu, wymieszać [15 s/ obr. wsteczne 2,5].",
      "Podawać na chlebie z ulubionymi warzywami."
    ],
    time: " minut",
    notes: "2 porcje",
    imgSrc: ""
  },
  {
    name: 'Mus czekoladowy',
    whichMeal: "drugie śniadanie",
    kcal: 310,
    mom: null,
    me: null,
    ingredients: [
      {ingrName: 'awokado', amount: "1/2", unit: 'sztuki'},
      {ingrName: 'banan', amount: 1, unit: 'sztuka', gram: 120},
      {ingrName: 'kakao', amount: 1, unit: 'łyżka', gram: 10},
      {ingrName: 'napój migdałowy (lub dowolne mleko roślinne)', amount: "60-120", unit: 'g (w zależności od pożądanej konsystencji)'},
    ],
    steps: [
      "Wszystkie składniki zmiksować na gładki mus [30 s/ obr 8]."
    ],
    time: " minut",
    notes: "",
    imgSrc: ""
  },
  {
    name: 'Sałatka CEZAR',
    whichMeal: "obiad",
    kcal: 400,
    mom: null,
    me: null,
    ingredients: [
      {group: 'SOS (na 2 porcje):'},
      {ingrName: 'czosnek', amount: 1, unit: 'ząbek'},
      {ingrName: 'jogurt naturalny', amount: 4, unit: 'łyżki'},
      {ingrName: 'musztarda', amount: 2, unit: 'łyżeczki'},
      {ingrName: 'sok z cytryny', amount: "kilka", unit: 'kropli'},
      {ingrName: 'sól, pieprz, odrobina sosu sojowego'},
      {group: 'Sałatka (na 1 porcję):'},
      {ingrName: 'jajko', amount: 1, unit: 'sztuka'},
      {ingrName: 'sałata lodowa', amount: "1/2", unit: 'sztuki'},
      {ingrName: 'filet z piersi kurczaka', amount: "100-120", unit: 'g'},
      {ingrName: 'Przyprawy do kurczaka: papryka słodka, cayenne/chili/ostra papryka, pieprz ziołowy, sól, mielona kolendra (symbolicznie), pieprz'},
      {ingrName: 'oliwa z oliwek', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'pomidorki koktajlowe', amount: 5, unit: 'sztuk'},
      {ingrName: 'parmezan tarty', amount: 1, unit: 'łyżka', gram: 12},
      {ingrName: 'chleb żytni, razowy', amount: "1/2", unit: 'kromki'},
    ],
    steps: [
      "Do naczynia włożyć czosnek, rozdrobnić [3 s/ obr. 8]. Zgarnąć ze ścianek.",
      "Dodać jogurt, musztardę, sok z cytryny i przyprawy, mieszać [10 s/ obr. 5]. Umyć naczynie.",
      "Jajko umieścić w koszyczku, gotować na półmiękko: 400 g wody, [12-13min/ Varoma/ obr.1], pokroić w ósemki.",
      "Sałatę drobno poszatkować i wymieszać dokładnie z sosem w głębokiej misce.",
      "Kurczaka pokroić na płaskie kawałki, przyprawić, skropić oliwą i ugrillować na suchej patelni z dwóch stron lub upiec w piekarniku w 180°C.",
      "W międzyczasie pokroić chleb w kosteczkę i dorzucić na 2-3 minuty do piekarnika.",
      "Do sałaty dodać pomidorki, mięso i jajko.",
      "Podawać posypaną parmezanem, świeżo zmielonym np. kolorowym pieprzem oraz grzankami z chleba żytniego."
    ],
    time: " minut",
    notes: "",
    imgSrc: ""
  },
    {
    name: 'Krem z gruszki i pietruszki',
    whichMeal: "kolacja",
    kcal: 300,
    mom: null,
    me: null,
    ingredients: [
      {ingrName: 'pietruszka, korzeń', amount: 4, unit: 'sztuki', gram: 320},
      {ingrName: 'masło klarowane', amount: 1, unit: 'łyżka', gram: 16},
      {ingrName: 'gruszka', amount: 1, unit: 'sztuka'},
      {ingrName: 'curry', amount: 1, unit: 'łyżeczka'},
      {ingrName: 'sól, pieprz'},
      {ingrName: 'bulion warzywny', amount: 500, unit: 'g'},
      {ingrName: 'boczek wędzony', amount: 4, unit: 'plastry (2 na porcję)', gram: 60},
    ],
    steps: [
      "Pietruszkę rozdrobnić [3 s/ obr. 5] i dusić na masełku [5 min/ 120°C/ obr. 1].",
      "Dodać gruszkę pokrojoną w grubą kostkę i dusić kolejne [3 min/ 120°C/ obr. 1].",
      "Dodać curry, sól i pieprz i zalać bulionem. Gotować ok. [15 minut/ 100°C/ obr. 1].",
      "Zblendować na gładką masę [1 min/ obr.10].",
      "Podawać z chipsami z boczku wędzonego (2-3 minuty w piekarniku, 200°C, funkcja grill)."
    ],
    time: " minut",
    notes: "2 porcje",
    imgSrc: ""
  },

  
  {
    name: '',
    whichMeal: "śniadanie",
    kcal: 0,
    mom: null,
    me: null,
    ingredients: [
      {ingrName: '', amount: 1, unit: 'sztuka', gram: 150},
    ],
    steps: [
      ""
    ],
    time: " minut",
    notes: "",
    imgSrc: ""
  },









  {
    name: 'Owsianka z owocami',
    whichMeal: "śniadanie",
    kcal: 400,
    mom: null,
    me: null,
    ingredients: [
      {ingrName: 'jabłko (małe)', amount: 1, unit: 'sztuka', gram: 150},
      {ingrName: 'woda', amount: "2/3", unit: 'szklanki', gram: 180},
      {ingrName: 'płatki owsiane', amount: "3", unit: 'łyżki', gram: 30},
      {ingrName: 'cynamon', amount: "1", unit: 'szczypta'},
      {ingrName: 'miód', amount: "1", unit: 'łyżka', gram: 25},
      {ingrName: 'borówki', amount: "1", unit: 'garść', gram: 50},
      {ingrName: 'maliny', amount: "1", unit: 'garść', gram: 50},
      {ingrName: 'płatki migdałów', amount: "1", unit: 'łyżka', gram: 10},
    ],
    steps: [
      "Jabłko obrać, pokroić na ćwiartki i rozdrobnić [4 s / obr. 5]. Przełożyć do innego naczynia.",
      "Do naczynia miksującego wlać wodę, dodać płatki owsiane i cynamon.",
      "Gotować [10 min / 95&deg;C / obr. wsteczne 1].",
      "Dodać jabłko i miód, wymieszać z zatkaną miarką [10 s / obr. wsteczne 1,5].",
      "Przełożyć do miseczki, posypać owocami i płatkami migdałów."
    ],
    time: "15 minut",
    notes: "",
    imgSrc: ""
  },
    {
    name: 'Sałatka z pomarańczą, mozzarellą i orzechami włoskimi',
    whichMeal: "drugie śniadanie",
    kcal: 330,
    mom: null,
    me: null,
    ingredients: [
      {ingrName: 'szpinak', amount: 2, unit: 'garście'},
      {ingrName: 'ser mozzarella', amount: "50", unit: 'g'},
      {ingrName: 'pomarańcza', amount: "1/2", unit: 'sztuki'},
      {ingrName: 'oliwa', amount: "1", unit: 'łyżeczka'},
      {ingrName: 'miód', amount: "1", unit: 'łyżeczka'},
      {ingrName: 'ocet balsamiczny', amount: "1", unit: 'łyżeczka'},
      {ingrName: 'orzechy włoskie', amount: "1", unit: 'łyżka', gram: 15}
    ],
    steps: [
      "Do miseczki wrzucić szpinak, pokrojone w kosteczkę pomarańczę i mozzarellę.",
      "Polać dressingiem z oliwy, miodu i octu balsamicznego, posypać orzechami."
    ],
    time: "5 minut",
    notes: "",
    imgSrc: ""
  },
  {
    name: 'Kurczak z sosem czosnkowym i warzywami',
    whichMeal: "obiad",
    kcal: 420,
    mom: null,
    me: null,
    ingredients: [
      {ingrName: 'filet z piersi kurczaka', amount: "1/2", unit: 'sztuki', gram: 150},
      {ingrName: 'marynata'},
      {ingrName: 'oliwa z oliwek', amount: "1", unit: 'łyżka', gram: 10},
      {ingrName: 'fasolka szparagowa/warzywa na parze', amount: "200", unit: 'g'},
      {ingrName: 'czosnek granulowany'},
      {ingrName: 'sezam', amount: "1", unit: 'łyżka', gram: 10},
      {ingrName: 'czosnek', amount: "1", unit: 'ząbek'},
      {ingrName: 'jogurt naturalny, gęsty', amount: "2", unit: 'łyżki', gram: 40},
      {ingrName: 'sól, pieprz, oregano'},
      {ingrName: 'koperek', amount: "1", unit: 'łyżka'},
    ],
    steps: [
      "Filet z kurczaka lekko rozbić, marynować w przyprawach z oliwą, ułożyć w głębokim wkładzie (można też ugrillować), a w górnej wkładce umieścić fasolkę szparagową/warzywa (można lekko osolić).",
      "Do naczynia miksującego wlać 600g wody (lub bulionu). Gotować mięso i warzywa [ok. 20 min / ??? &deg;C / obr. wsteczne 1]",
      "W miseczce wymieszać jogurt, czosnek przeciśnięty przez praskę i koperek (można pominąć), doprawić do smaku.",
      "Mięso podawać z sosem i z fasolką szparagową lub warzywami wymieszanymi z czosnkiem granulowanym i posypanym uprażonym na suchej patelni sezamem."
    ],
    time: "35 minut + marynowanie",
    notes: "Marynata - według uznania, np. sól, pieprz, papryka słodka, zioła prowansalskie lub przyprawa do grilla (bez e-dodatków)",
    imgSrc: ""
  },
    {
    name: 'Łosoś grillowany/gotowany na parze z tzatziki',
    whichMeal: "obiad",
    kcal: 410,
    mom: null,
    me: null,
    ingredients: [
      {ingrName: 'ogórek', amount: 1, unit: 'sztuka', gram: 100},
      {ingrName: 'czosnek', amount: 1, unit: 'ząbek'},
      {ingrName: 'jogurt grecki', amount: 2, unit: 'łyżki', gram: 40},
      {ingrName: 'erytrol', amount: "1/2", unit: 'łyżeczki'},
      {ingrName: 'ocet winny/jabłkowy', amount: "1", unit: 'łyżeczka'},
      {ingrName: 'łosoś, świeży', amount: 150, unit: 'g'},
      {ingrName: 'sól, pieprz ziołowy', amount: 'do smaku'},
      {ingrName: 'sok z cytryny', amount: "1", unit: 'łyżeczka'},
      {ingrName: 'fasolka szparagowa/warzywa na parze', amount: 200, unit: 'g'},
    ],
    steps: [
      "Do naczynia miksującego włożyć ogórek i odrobinę posolić, rozdrobnić [3 s / obr. 5]. Przełożyć do koszyczka i usunąć nadmiar wody dociskając dłońmi.",
      "Do naczynia włożyć czosnek, rozdrobnić [3 s / obr. 7].",
      "Dodać ogórki, jogurt grecki, erytrol i ocet. Wymieszać [10 s / obr. wsteczne 1,5], przełożyć do miseczki i wymieszać z ogórkami. Umyć naczynie miksujące.",
      "Rybę przyprawić solą, pieprzem ziołowym i skropić sokiem z cytryny.",
      "Ułożyć na górnym wkładzie (można też zapiekać w piekarniku). W dolnej przystawce umieścić warzywa (można lekko osolić). Do naczynia miksującego wlać 500g wody, nałożyć przystawki, gotować na parze [15-20 min / ??? / obr. 1].",
      "Rybę podawać z sosem tzatziki i fasolką szparagową/warzywami (można doprawić solą, czosnkiem granulowanym)."
    ],
    time: "30 minut",
    notes: "",
    imgSrc: ""
  },
      {
    name: 'Kanapki z śródziemnomorską pastą',
    whichMeal: "kolacja",
    kcal: 280,
    mom: null,
    me: null,
    ingredients: [
      {ingrName: 'bazylia (świeża)', amount: 1, unit: 'garść'},
      {ingrName: 'oliwki czarne', amount: 5, unit: 'sztuk', gram: 20},
      {ingrName: 'pomidory suszone w oleju', amount: 6, unit: 'plastrów', gram: 40},
      {ingrName: 'ser typu "Feta"', amount: "1/2", unit: 'kostki', gram: 100},
      {ingrName: 'serek śmietankowy, naturalny (np. Almette)', amount: "2", unit: 'łyżki', gram: 50},
      {ingrName: 'koncentrat pomidorowy 30%', amount: 1, unit: 'łyżeczka', gram: 15},
      {ingrName: 'chleb żytni', amount: 2, unit: "kromki"},
      {ingrName: 'warzywa (np. pomidor, ogórek, papryka, kiełki, szpinak/sałata)'},
    ],
    steps: [
      "Do naczynia miksującego włożyć bazylię, rozdrobnić [3 s / obr. 8], zgarnąć na dno.",
      "Dodać oliwki, rozdrobnić [10 s / obr. 4,5].",
      "Dodać odsączone pomidory, ser feta, twarożek, koncentrat pomidorowy, rozdrobnić [8 s / obr. 8]. Gdyby pasta była zbyt gęsta, dodać 2-3 łyżki jogurtu.",
      "Podawać na chlebie, z warzywami."
    ],
    time: "5 minut",
    notes: "",
    imgSrc: ""
  },
];